In [109]:
import pandas as pd
import numpy as np
import scipy as sp
import os
from scipy.sparse import csr_matrix, lil_matrix, eye, diags
from scipy.sparse.linalg import spsolve
from openpyxl import load_workbook
import requests
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from goatools.obo_parser import GODag
from collections import Counter
import math
import re

In [ ]:
dir_name = os.path.join("..", "Data")

df_human = pd.read_csv(os.path.join(dir_name, "9606.protein.links.full.v12.0.txt"), sep=" ")
df_rvfv = pd.read_csv(os.path.join(dir_name, "string_interactions.tsv"), sep="\t")

df_denv = pd.read_csv(os.path.join(dir_name, "den_2_interactions.tsv"), sep="\t")

df_lasv = pd.read_csv(os.path.join(dir_name, "lassa_interactions.tsv"), sep="\t")

df_id_conversions = pd.read_csv(os.path.join(dir_name, "HUMAN_9606_idmapping_selected.tab"), sep="\t")
df_id_conversions.columns = ['Uniprot_ID', 'uk1', 'uk2', 'uk3', 'uk4', 'uk5', 'GO_IDs', 'uk6', 'uk7', 'uk8', 'uk9', 'uk10', 'uk11', 'uk12', 'uk13', 'uk14', 'uk15', 'uk16', 'ENSG', 'ENST', 'ENSP', 'uk17']

uniprot_ids = pd.read_csv(os.path.join(dir_name, "h_proteome_int_partners.tsv"), sep="\t")

#intact_interactions = pd.read_csv(os.path.join(dir_name, "intact_h_ints.txt"), sep="\t")

godag = GODag(os.path.join(dir_name, "go.obo"))

C:\Users\socce\AppData\Local\Temp\ipykernel_11360\3292353881.py:10: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_id_conversions = pd.read_csv(os.path.join(dir_name, "HUMAN_9606_idmapping_selected.tab"), sep="\t")

..\Data\go.obo: fmt(1.2) rel(2024-11-03) 43,983 Terms

In [204]:
intact_interactions = pd.read_csv(os.path.join(dir_name, "intact_h_ints.txt"), sep="\t")

In [206]:
intact_interactions = intact_interactions.rename(columns={'#ID(s) interactor A': 'int_A', 'ID(s) interactor B': 'int_B'})

In [207]:
intact_interactions

,int_A,int_B,Alt. ID(s) interactor A,Alt. ID(s) interactor B,Alias(es) interactor A,Alias(es) interactor B,Interaction detection method(s),Publication 1st author(s),Publication Identifier(s),Taxid interactor A,...,Checksum(s) interactor A,Checksum(s) interactor B,Interaction Checksum(s),Negative,Feature(s) interactor A,Feature(s) interactor B,Stoichiometry(s) interactor A,Stoichiometry(s) interactor B,Identification method participant A,Identification method participant B
0,uniprotkb:P46109,uniprotkb:Q13191,intact:EBI-910|ensembl:ENSP00000346300.3|ensem...,intact:EBI-744027|uniprotkb:Q63Z43|uniprotkb:A...,psi-mi:crkl_human(display_long)|uniprotkb:CRKL...,psi-mi:cblb_human(display_long)|uniprotkb:Sign...,"psi-mi:""MI:0019""(coimmunoprecipitation)",Elly et al. (1999),pubmed:10022120|mint:MINT-6731034,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:1YwlbUPPuijisz7AJM4Qkp7yJBI9606,rogid:cJ5eLH0TMyM6OtmS1sM3rhsrsIk9606,intact-crc:3E8C78E5182277F9|rigid:rbINobWATHyE...,False,-,binding-associated region:702-715(MINT-8028122...,-,-,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)"
1,uniprotkb:Q13191,uniprotkb:P46109,intact:EBI-744027|uniprotkb:Q63Z43|uniprotkb:A...,intact:EBI-910|ensembl:ENSP00000346300.3|ensem...,psi-mi:cblb_human(display_long)|uniprotkb:Sign...,psi-mi:crkl_human(display_long)|uniprotkb:CRKL...,"psi-mi:""MI:0019""(coimmunoprecipitation)",Elly et al. (1999),pubmed:10022120|mint:MINT-6731034,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:cJ5eLH0TMyM6OtmS1sM3rhsrsIk9606,rogid:1YwlbUPPuijisz7AJM4Qkp7yJBI9606,intact-crc:A338A91115FF963B|rigid:rbINobWATHyE...,False,phosphorylated residue:665-665(MINT-8030529)|b...,-,-,-,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)"
2,uniprotkb:P61769,uniprotkb:P01899,intact:EBI-714718|uniprotkb:P01884|uniprotkb:Q...,intact:EBI-6934701|intact:MINT-85762|ensembl:E...,psi-mi:b2mg_human(display_long)|uniprotkb:B2M(...,psi-mi:ha11_mouse(display_long)|uniprotkb:H2-D...,"psi-mi:""MI:0114""(x-ray crystallography)",Glithero et al. (1999),pubmed:10023771|mint:MINT-5211154,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:P08CZT3zl5vRrh+ELuLhkCM7jR89606,rogid:YTnZIrThEnQXw8/8vB9UFDqffrE10090,intact-crc:FA0C810A18B8D863|rigid:jZIz0sh7tyBE...,False,tag:?-?(MINT-363686),tag:?-?(MINT-363679),1,1,"psi-mi:""MI:0078""(nucleotide sequence identific...","psi-mi:""MI:0078""(nucleotide sequence identific..."
3,uniprotkb:P36897,uniprotkb:P62942,intact:EBI-1027557|uniprotkb:Q6IR47|uniprotkb:...,intact:EBI-1027571|uniprotkb:P20071|uniprotkb:...,psi-mi:tgfr1_human(display_long)|uniprotkb:TGF...,psi-mi:fkb1a_human(display_long)|uniprotkb:FKB...,"psi-mi:""MI:0114""(x-ray crystallography)",Huse et al. (1999),pubmed:10025408,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:rbevTt5rBnZGnKMpGArFIM0ZVUQ9606,rogid:3eikHNIIVs8AFM7PYVWurI/9KUY9606,intact-crc:CA0B99C9AE03491A|rigid:HgdaFdXmFwTM...,False,sufficient binding region:162-503,sufficient binding region:2-108,4,4,"psi-mi:""MI:0396""(predetermined participant)","psi-mi:""MI:0396""(predetermined participant)"
4,uniprotkb:F1MRS1,uniprotkb:A6H772,intact:EBI-2638538|ensembl:ENSBTAP00000012949.7,intact:EBI-2638542|ensembl:ENSBTAP00000017178.3,psi-mi:f1mrs1_bovin(display_long)|uniprotkb:PP...,psi-mi:pp4c_bovin(display_long)|uniprotkb:PPP4...,"psi-mi:""MI:0091""(chromatography technology)",Kloeker et al. (1999),pubmed:10026142|imex:IM-18951,"taxid:9913(bovin)|taxid:9913(""Bos taurus (Bovi...",...,rogid:2gwaiE47E+xg/dB77SsSky4Fpow9913,rogid:1x3NwIpQ/T3bO/yHgAZUDqNV4989913,intact-crc:9F6893D16587DB54|rigid:5NkK9m3G93tl...,False,-,-,1,1,"psi-mi:""MI:0082""(peptide massfingerprinting)","psi-mi:""MI:0082""(peptide massfingerprinting)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089003,uniprotkb:Q9UKG1,uniprotkb:Q96A54,intact:EBI-741243|intact:EBI-28979536|uniprotk...,intact:EBI-1632076|uniprotkb:Q9Y360|uniprotkb:...,psi-mi:dp13a_human(display_long)|uniprotkb:Ada...,psi-mi:paqr1_human(display_long)|uniprotkb:ADI...,"psi-mi:""MI:0055""(fluorescent resonance energy ...",JianPing et al. (2008),pubmed:unassigned85,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:v94zzPKDww+kZxRttd3FHIXIx/w9606,rogid:cwGOTdI1IOoJh6ru/aDwj+aC3Ro9606,intact-crc:B6C0166EFF96AD4F|rigid:kMG/uLNmx+SZ...,False,cyan fluorescent protein tag:?-?,yellow fluorescent protein tag:?-?,-,-,"psi-mi:""MI:0867""(tag visualisation by fluoresc...","psi-mi:""MI:0867""(tag visualisation by fluoresc..."
1089004,uniprotkb:Q9UKG1,uniprotkb:Q86V24,intact:EBI-741243|intact:EBI-28979536|uniprotk...,intact:EBI-1769445|uniprotkb:Q9H737|ensembl:EN...,psi-mi:dp13a_human(display_long)|uniprotkb:Ada...,psi-mi:paqr2_human(display_long)|uniprotkb:ADI...,"psi-mi:""MI:0055""(fluorescent resonance energy ...",JianPing et al. (2008),pubmed:unassigned85,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:v94zzPKDww+kZxRttd3FHIXIx/w9606,rogid:ItBxo7yJY2O7ibVCtV8MMXqTrDA9606,intact-crc:12B768D41C11E789|rigid:QWfDXgIeIcnR...,False,cyan fluorescent protein tag:?-?,yellow fluorescent protein tag:?-?,-,-,"psi-mi:""MI:0867""(tag visualisation by fluoresc...","psi-mi:""MI:0867""(tag visualisation by fluoresc..."
1089005,uniprotkb:Q96A54,uniprotkb:Q96A54,intact:EBI-1632076|uniprotkb:Q9Y360|uniprotkb:...,intact:EBI-1632076|uniprotkb:Q9Y360|uniprotkb:...,psi-mi:paqr1_human(display_long)|uniprotkb:ADI...,psi-mi:paqr1_human(display_long)|uniprotkb:ADI...,"psi-mi:""MI:0809""(bimolecular fluorescence comp...",JianPing et al. (2008),pubmed:unassigned85,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:cwGOTdI1IOoJh6ru/aDwj+aC3Ro9606,rogid:cwGOTdI1IOoJh6ru/aDwj+aC3Ro9606,intact-crc:EA8075405EBA3845|rigid:iYJTKX22cXTw...,False,yellow fluorescent protein tag:?-?,yellow fluorescent protein tag:?-?,-,-,"psi-mi:""MI:0867""(tag visualisation by fluoresc...","psi-mi:""MI:0867""(tag visualisation by fluoresc..."
1089006,uniprotkb:P08670,uniprotkb:P08670,intact:EBI-353844|uniprotkb:Q15867|uniprotkb:Q...,intact:EBI-353844|uniprotkb:Q15867|uniprotkb:Q...,psi-mi:vime_human(display_long)|uniprotkb:VIM(...,psi-mi:vime_human(display_long)|uniprotkb:VIM(...,"psi-mi:""MI:0809""(bimolecular fluorescence comp...",JianPing et al. (2008),pubmed:unassigned85,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:GhAhVuXMNxi6P5J0CfNi5l9bjRk9606,rogid:GhAhVuXMNxi6P5J0CfNi5l9bjRk9606,intact-crc:6FC33B547E645FAA|rigid:pQQJ2JMO+95+...,False,yellow fluorescent protein tag:?-?,yellow fluorescent protein tag:?-?,-,-,"psi-mi:""MI:0867""(tag visualisation by fluoresc...","psi-mi:""MI:0867""(tag visualisation by fluoresc..."
1089007,uniprotkb:Q9UKG1,uniprotkb:Q96A54,intact:EBI-741243|intact:EBI-28979536|uniprotk...,intact:EBI-1632076|uniprotkb:Q9Y360|uniprotkb:...,psi-mi:dp13a_human(display_long)|uniprotkb:Ada...,psi-mi:paqr1_human(display_long)|uniprotkb:ADI...,"psi-mi:""MI:0809""(bimolecular fluorescence comp...",JianPing et al. (2008),pubmed:unassigned85,taxid:9606(human)|taxid:9606(Homo sapiens),...,rogid:v94zzPKDww+kZxRttd3FHIXIx/w9606,rogid:cwGOTdI1IOoJh6ru/aDwj+aC3Ro9606,intact-crc:7CDBBBC2F631FECD|rigid:kMG/uLNmx+SZ...,False,yellow fluorescent protein tag:?-?,yellow fluorescent protein tag:?-?,-,-,"psi-mi:""MI:0867""(tag visualisation by fluoresc...","psi-mi:""MI:0867""(tag visualisation by fluoresc..."

In [59]:
# Get unique human ENSPs from the STRING DB

unique_prots_ensp = set(df_human["protein1"]) | set(df_human["protein2"])
unique_prots_ensp = [i.split('.')[1] for i in unique_prots_ensp]

In [60]:
# Full list of ENSP IDs and uniprot conversions from uniprot conversion table

ensp_id_list = list(df_id_conversions["ENSP"])
ensp_id_list = [str(i).split('; ') for i in ensp_id_list]

In [61]:
# 1D list of ENSPs included in the conversion table

flat_ensp_id_list = [id.split('.')[0] for sublist in ensp_id_list for id in sublist]

In [62]:
# Full list of Uniprot IDs from uniprot conversion table

full_uniprot_id_list = list(df_id_conversions["Uniprot_ID"])

In [63]:
# Build conversion dict containing all uniprot IDs and ENSP IDs from conversion table

ensp_to_uniprot = {}

for keys, value in zip(ensp_id_list, full_uniprot_id_list):
    if isinstance(keys, list):
        for key in keys:  
            ensp_to_uniprot[key.split('.')[0]] = value
    else:
        ensp_to_uniprot[keys] = value

In [64]:
# List of ENSP IDs in the interaction dataset that are NOT included in the Uniprot conversion table

ensps_cut_out = [e for e in unique_prots_ensp if e not in flat_ensp_id_list]

In [65]:
# Map all human Uniprot IDs to their protein names

total_uniprot_id_list = list(uniprot_ids['Entry'])
total_prot_names = list(uniprot_ids['Protein names'])

uniprot_to_name_map = {u:g for u,g in zip(total_uniprot_id_list, total_prot_names)}

In [160]:
uniprot_to_name_map

{'A0A024R1X5': 'Beclin-1',
 'A0A024R274': 'Mothers against decapentaplegic homolog (MAD homolog) (Mothers against DPP homolog) (SMAD family member)',
 'A0A024R324': 'Transforming protein RhoA',
 'A0A024R6A3': 'Presenilin (EC 3.4.23.-)',
 'A0A024R7I7': 'Ras-related protein Rab-3',
 'A0A024RA31': 'Aquaporin-1 (Aquaporin-CHIP) (Water channel protein for red blood cells and kidney proximal tubule)',
 'A0A068F658': 'Glucosylceramidase (EC 3.2.1.45)',
 'A0A087WV00': 'Diacylglycerol kinase (DAG kinase) (EC 2.7.1.107)',
 'A0A087WZT3': 'BOLA2-SMG1P6 readthrough',
 'A0A087X0K9': 'Tight junction protein 1',
 'A0A087X1C5': 'Putative cytochrome P450 2D7 (EC 1.14.14.1)',
 'A0A087X296': 'Prostaglandin G/H synthase 1 (EC 1.14.99.1) (Cyclooxygenase-1) (Prostaglandin H2 synthase 1) (Prostaglandin-endoperoxide synthase 1)',
 'A0A090N7W4': 'Cell division protein kinase 5',
 'A0A090N8E9': 'Histone-lysine N-methyltransferase EZH2 (EC 2.1.1.356)',
 'A0A0A0MR05': 'Target of rapamycin complex subunit LST8 (Protein GbetaL) (TORC subunit LST8) (mLST8) (G protein beta subunit-like) (Mammalian lethal with SEC13 protein 8)',
 'A0A0A0MSN4': 'Angiotensin-converting enzyme (EC 3.4.-.-)',
 'A0A0B4J1S7': 'protein-tyrosine-phosphatase (EC 3.1.3.48)',
 'A0A0B4J2F0': 'Protein PIGBOS1 (PIGB opposite strand protein 1)',
 'A0A0C5B5G6': 'Mitochondrial-derived peptide MOTS-c (Mitochondrial open reading frame of the 12S rRNA-c)',
 'A0A0K0K1J8': 'Adenylate cyclase type 10 (EC 4.6.1.1)',
 'A0A0K0K1K3': 'adenylate cyclase (EC 4.6.1.1)',
 'A0A0K2S4Q6': 'Protein CD300H (CD300 antigen-like family member H)',
 'A0A0S2Z310': 'Serine/threonine-protein kinase receptor (EC 2.7.11.30)',
 'A0A0S2Z366': 'Medium-chain specific acyl-CoA dehydrogenase, mitochondrial (EC 1.3.8.7)',
 'A0A0S2Z381': 'Adenosine deaminase (EC 3.5.4.4) (Adenosine aminohydrolase)',
 'A0A0S2Z383': 'Homeobox protein Nkx-2.5 (Homeobox protein NK-2 homolog E)',
 'A0A0S2Z391': 'BCL2-antagonist/killer 1 isoform 1',
 'A0A0S2Z3A9': 'Bardet-Biedl syndrome 4 isoform 1 (Bardet-Biedl syndrome 4, isoform CRA_a)',
 'A0A0S2Z3C5': 'Bcl-2-like protein 1 (Apoptosis regulator Bcl-X)',
 'A0A0S2Z3C7': 'Tumor necrosis factor receptor superfamily member 5 (B-cell surface antigen CD40) (CD40L receptor)',
 'A0A0S2Z3D5': 'Apolipoprotein E',
 'A0A0S2Z3Q4': 'Adapter molecule crk',
 'A0A0S2Z3W3': 'Beta-hexosaminidase subunit alpha (EC 3.2.1.52) (Beta-N-acetylhexosaminidase subunit alpha) (N-acetyl-beta-glucosaminidase subunit alpha)',
 'A0A0S2Z3W6': 'Sodium/potassium-transporting ATPase subunit alpha',
 'A0A0S2Z478': 'Corticoliberin (Corticotropin-releasing factor) (Corticotropin-releasing hormone)',
 'A0A0S2Z4C6': 'Serine/threonine-protein phosphatase (EC 3.1.3.16)',
 'A0A0S2Z4D1': 'non-specific serine/threonine protein kinase (EC 2.7.11.1)',
 'A0A0S2Z4G9': 'Ring finger protein 6 isoform 2',
 'A0A0S2Z4N5': 'Tumor protein 63 (p63)',
 'A0A0S2Z4R0': 'Axin-1 (Axis inhibition protein 1)',
 'A0A0S2Z4Z8': 'Receptor-interacting serine-threonine kinase 2 isoform 1',
 'A0A0S2Z5J4': 'Adaptor-related protein complex 3 beta 1 subunit isoform 1',
 'A0A0S2Z5U8': 'Dystrobrevin binding protein 1 isoform 1',
 'A0A0S2Z5X4': 'Zinc finger protein 688 isoform 4',
 'A0A0U1RQF0': 'Fatty acid synthase (EC 1.1.1.100) (EC 1.3.1.39) (EC 2.3.1.38) (EC 2.3.1.39) (EC 2.3.1.41) (EC 2.3.1.85) (EC 3.1.2.14) (EC 4.2.1.59)',
 'A0A0U1RQS4': 'SH3 and multiple ankyrin repeat domains 3',
 'A0A0U1RRE5': 'Negative regulator of P-body association (P-body dissociating protein) (Protein NoBody)',
 'A0A140VJC8': 'Amyloid-beta A4 protein',
 'A0A140VJE4': 'Testicular tissue protein Li 18',
 'A0A140VJG8': 'Catechol O-methyltransferase (EC 2.1.1.6)',
 'A0A140VJL2': 'Hydroxymethylglutaryl-CoA synthase (HMG-CoA synthase) (EC 2.3.3.10) (3-hydroxy-3-methylglutaryl coenzyme A synthase)',
 'A0A140VJL3': 'Hypoxanthine phosphoribosyltransferase (EC 2.4.2.8)',
 'A0A140VJL9': 'Delta-aminolevulinic acid dehydratase (EC 4.2.1.24)',
 'A0A140VJM0': 'Testicular tissue protein Li 96 (Testicular tissue protein Li 98)',
 'A0A140VJU3': 'Testicular tissue protein Li 170',
 'A0A140VK09': 'Calcium and integrin-binding protein 1 (Calmyrin)',
 'A0A140VK13': 'Carnitine O-palmitoyltransferase 2, mitochondrial (EC 2.3.1.21) (Carnitine palmitoyltransferase II)',
 'A0A140VKC4': 'Methyl-CpG-binding protein 2 (MeCp-2 protein) (MeCp2)',
 'A0A1B0GTB8': 'Carnitine O-palmitoyltransferase 2, mitochondrial (EC 2.3.1.21) (Carnitine palmitoyltransferase II)',
 'A0A1B0GTW7': 'Ciliated left-right organizer metallopeptidase (EC 3.4.24.-) (Leishmanolysin-like peptidase 2)',
 'A0A1B0GV75': 'Carnitine O-palmitoyltransferase 2, mitochondrial (EC 2.3.1.21) (Carnitine palmitoyltransferase II)',
 'A0A1B0GVF3': 'Carnitine O-palmitoyltransferase 2, mitochondrial (EC 2.3.1.21) (Carnitine palmitoyltransferase II)',
 'A0A1B0GWC0': 'Carnitine O-palmitoyltransferase 2, mitochondrial (EC 2.3.1.21) (Carnitine palmitoyltransferase II)',
 'A0A1B0GWI1': 'Coiled-coil domain containing 196',
 'A0A1B1RVA9': 'Lipoprotein lipase (LPL) (EC 3.1.1.34)',
 'A0A1L1UHR1': 'Non-selective voltage-gated ion channel VDAC1 (Voltage-dependent anion-selective channel protein 1)',
 'A0A1U9X797': 'Alpha-tubulin N-acetyltransferase 1 (Alpha-TAT) (Alpha-TAT1) (TAT) (EC 2.3.1.108) (Acetyltransferase mec-17 homolog)',
 'A0A1U9X7R0': 'GABBR1',
 'A0A1U9X8X8': 'Corneodesmosin',
 'A0A218KGR2': 'Amyloid-beta A4 protein',
 'A0A2P9DU05': 'Rho-associated protein kinase (EC 2.7.11.1)',
 'A0A2R8Y4I8': 'Spastin (EC 5.6.1.1)',
 'A0A2U3TZR0': 'Spastin (EC 5.6.1.1)',
 'A0A2X0SFG1': 'Phosphatidylinositol 3-kinase regulatory subunit alpha (Phosphatidylinositol 3-kinase 85 kDa regulatory subunit alpha)',
 'A0A384MDY0': 'Catenin alpha-1',
 'A0A384ME25': 'Epididymis secretory sperm binding protein',
 'A0A384MED8': "Cytosolic purine 5'-nucleotidase (EC 2.7.1.77) (EC 3.1.3.5) (EC 3.1.3.99) (Cytosolic nucleoside phosphotransferase 5'N)",
 'A0A384N611': 'Protein Wnt',
 'A0A384N647': 'Adenylate kinase 4, mitochondrial (AK 4) (EC 2.7.4.10) (EC 2.7.4.6) (Adenylate kinase 3-like) (GTP:AMP phosphotransferase AK4)',
 'A0A384NL29': 'Superoxide dismutase (EC 1.15.1.1)',
 'A0A384NY87': 'Sterol carrier protein 2 (EC 2.3.1.155) (EC 2.3.1.16) (EC 2.3.1.176) (Acetyl-CoA C-myristoyltransferase) (Non-specific lipid-transfer protein) (Propanoyl-CoA C-acyltransferase) (SCP-2/3-oxoacyl-CoA thiolase) (SCP-2/thiolase) (SCP-chi) (Sterol carrier protein X)',
 'A0A384P5C6': 'Delta-like protein',
 'A0A384P5H7': 'Collagen, type VI, alpha 1, isoform CRA_b (Epididymis secretory sperm binding protein)',
 'A0A384P5Q0': 'Catalase (EC 1.11.1.6)',
 'A0A386NCS8': 'Phosphatidylinositol 3,4,5-trisphosphate 3-phosphatase and dual-specificity protein phosphatase PTEN (EC 3.1.3.16) (EC 3.1.3.48) (EC 3.1.3.67) (Phosphatase and tensin homolog)',
 'A0A3B3IRX2': 'Phospholipase A2 (EC 3.1.1.4)',
 'A0A3B3ISY9': 'Acylglycerol kinase, mitochondrial (EC 2.7.1.107) (EC 2.7.1.138) (EC 2.7.1.94) (Multiple substrate lipid kinase)',
 'A0A3B3ISZ0': 'Acylglycerol kinase, mitochondrial (EC 2.7.1.107) (EC 2.7.1.138) (EC 2.7.1.94) (Multiple substrate lipid kinase)',
 'A0A3B3ITD0': 'Acylglycerol kinase, mitochondrial (EC 2.7.1.107) (EC 2.7.1.138) (EC 2.7.1.94) (Multiple substrate lipid kinase)',
 'A0A499FJK2': 'Transforming growth factor beta',
 'A0A5F9ZH41': 'Vascular permeability factor',
 'A0A654IBU3': 'Gap junction protein',
 'A0A6G6A825': 'Phosphatidylinositol 3,4,5-trisphosphate 3-phosphatase and dual-specificity protein phosphatase PTEN (EC 3.1.3.16) (EC 3.1.3.48) (EC 3.1.3.67) (Phosphatase and tensin homolog)',
 'A0A6Q8PHB5': "Cytosolic purine 5'-nucleotidase (EC 2.7.1.77) (EC 3.1.3.5) (EC 3.1.3.99) (Cytosolic nucleoside phosphotransferase 5'N)",
 'A0A6Q8PHP0': "Cytosolic purine 5'-nucleotidase (EC 2.7.1.77) (EC 3.1.3.5) (EC 3.1.3.99) (Cytosolic nucleoside phosphotransferase 5'N)",
 'A0A7I2PJA1': 'GLI family zinc finger 2',
 'A0A7I2R3P8': 'NACHT, LRR and PYD domains-containing protein 3',
 'A0A7I2SVS4': 'Histone deacetylase (EC 3.5.1.98)',
 'A0A7P0T828': 'Prostaglandin G/H synthase 2 (EC 1.14.99.1) (Cyclooxygenase-2) (PHS II) (Prostaglandin H2 synthase 2) (Prostaglandin-endoperoxide synthase 2)',
 'A0A7U3JW18': 'Fibroblast growth factor (FGF)',
 'A0A7U3L6D0': 'Fibroblast growth factor (FGF)',
 'A0A8C8L3F5': 'Long-chain-fatty-acid--CoA ligase (EC 6.2.1.15) (EC 6.2.1.3) (Acyl-CoA synthetase) (Long-chain acyl-CoA synthetase)',
 'A0A8D9PH75': 'Glutamate receptor',
 'A0A8I5KW96': 'Adenylate kinase 4, mitochondrial (AK 4) (EC 2.7.4.10) (EC 2.7.4.6) (Adenylate kinase 3-like) (GTP:AMP phosphotransferase AK4)',
 'A0A8I5KZ76': 'Myotubularin (EC 3.1.3.95) (Phosphatidylinositol-3,5-bisphosphate 3-phosphatase) (Phosphatidylinositol-3-phosphate phosphatase)',
 'A0A8I5QJL1': 'Myotubularin (EC 3.1.3.95) (Phosphatidylinositol-3,5-bisphosphate 3-phosphatase) (Phosphatidylinositol-3-phosphate phosphatase)',
 'A0A8I5QJV9': 'Myotubularin (EC 3.1.3.95) (Phosphatidylinositol-3,5-bisphosphate 3-phosphatase) (Phosphatidylinositol-3-phosphate phosphatase)',
 'A0A8Q3SHM6': 'Neuroligin 1',
 'A0A8V8TPK6': 'Phosphatidylinositol 3,4,5-trisphosphate 3-phosphatase and dual-specificity protein phosphatase PTEN (EC 3.1.3.16) (EC 3.1.3.48) (EC 3.1.3.67) (Phosphatase and tensin homolog)',
 'A0A8V8TQ23': 'Choline/ethanolaminephosphotransferase 1 (EC 2.7.8.1) (EC 2.7.8.2) (EC 2.7.8.22) (1-alkenyl-2-acylglycerol choline phosphotransferase)',
 'A0A8V8TQL1': 'Choline/ethanolaminephosphotransferase 1 (EC 2.7.8.1) (EC 2.7.8.2) (EC 2.7.8.22) (1-alkenyl-2-acylglycerol choline phosphotransferase)',
 'A0A8V8TQX2': 'Phosphatidylinositol 3,4,5-trisphosphate 3-phosphatase and dual-specificity protein phosphatase PTEN (EC 3.1.3.16) (EC 3.1.3.48) (EC 3.1.3.67) (Phosphatase and tensin homolog)',
 'A0A8V8TRF3': 'Choline/ethanolaminephosphotransferase 1 (EC 2.7.8.1) (EC 2.7.8.2) (EC 2.7.8.22) (1-alkenyl-2-acylglycerol choline phosphotransferase)',
 'A0AAG2UV77': 'Triacylglycerol lipase (EC 3.1.1.3) (Pancreatic lipase)',
 'A0AV02': 'Solute carrier family 12 member 8 (Cation-chloride cotransporter 9)',
 'A0AV96': 'RNA-binding protein 47 (RNA-binding motif protein 47)',
 'A0AVF1': 'Intraflagellar transport protein 56 (Tetratricopeptide repeat protein 26) (TPR repeat protein 26)',
 'A0AVG3': 't-SNARE domain containing 1',
 'A0AVI4': 'E3 ubiquitin-protein ligase TM129 (EC 2.3.2.27) (RING-type E3 ubiquitin transferase TM129)',
 'A0AVK6': 'Transcription factor E2F8 (E2F-8)',
 'A0AVT1': 'Ubiquitin-like modifier-activating enzyme 6 (Ubiquitin-activating enzyme 6) (EC 6.2.1.45) (Monocyte protein 4) (MOP-4) (Ubiquitin-activating enzyme E1-like protein 2) (E1-L2)',
 'A0FGR8': 'Extended synaptotagmin-2 (E-Syt2) (Chr2Syt)',
 'A0FGR9': 'Extended synaptotagmin-3 (E-Syt3) (Chr3Syt)',
 'A0JLT2': 'Mediator of RNA polymerase II transcription subunit 19 (Lung cancer metastasis-related protein 1) (Mediator complex subunit 19)',
 'A0JNW5': 'Bridge-like lipid transfer protein family member 3B (Syntaxin-6 Habc-interacting protein of 164 kDa) (UHRF1-binding protein 1-like)',
 'A0JP26': 'POTE ankyrin domain family member B3',
 'A0M8Q6': 'Immunoglobulin lambda constant 7 (Ig lambda-7 chain C region)',
 'A0MZ66': 'Shootin-1 (Shootin1)',
 'A0N0X8': 'Cytochrome P450 1A (EC 1.14.14.1)',
 'A0PJK1': 'Sodium/mannose cotransporter SLC5A10 (Sodium/glucose cotransporter 5) (Na(+)/glucose cotransporter 5) (Solute carrier family 5 member 10)',
 'A0PJY2': 'Fez family zinc finger protein 1 (Zinc finger protein 312B)',
 'A0PK00': 'Transmembrane protein 120B',
 'A0PK11': 'Clarin-2',
 'A1A4S6': 'Rho GTPase-activating protein 10 (GTPase regulator associated with focal adhesion kinase 2) (GRAF2) (Graf-related protein 2) (Rho-type GTPase-activating protein 10)',
 'A1A4Y4': 'Immunity-related GTPase family M protein (EC 3.6.5.-) (Immunity-related GTPase family M protein 1) (Interferon-inducible protein 1) (LPS-stimulated RAW 264.7 macrophage protein 47 homolog) (LRG-47)',
 'A1A519': 'Protein FAM170A (Zinc finger domain-containing protein) (Zinc finger protein ZNFD)',
 'A1A5B4': 'Anoctamin-9 (Transmembrane protein 16J) (Tumor protein p53-inducible protein 5) (p53-induced gene 5 protein)',
 'A1A5C7': 'Solute carrier family 22 member 23',
 'A1E959': 'Odontogenic ameloblast-associated protein (Apin)',
 'A1KXE4': 'Myelin-associated neurite-outgrowth inhibitor (Mani) (p20)',
 'A1KZ92': 'Probable oxidoreductase PXDNL (EC 1.-.-.-) (Cardiac peroxidase) (Inactive peroxidasin-like protein) (Polysomal ribonuclease 1) (PRM1) (Vascular peroxidase 2)',
 'A1L0T0': '2-hydroxyacyl-CoA lyase 2 (EC 4.1.2.-) (Acetolactate synthase-like protein) (IlvB-like protein)',
 'A1L167': 'Ubiquitin-conjugating enzyme E2Q-like protein 1 (EC 2.3.2.23) (E2Q-like ubiquitin-conjugating enzyme 1)',
 'A1L190': 'Synaptonemal complex central element protein 3 (Testis highly expressed gene 2 protein) (THEG-2)',
 'A1L390': 'Pleckstrin homology domain-containing family G member 3 (PH domain-containing family G member 3)',
 'A1L3X0': 'Very long chain fatty acid elongase 7 (EC 2.3.1.199) (3-keto acyl-CoA synthase ELOVL7) (ELOVL fatty acid elongase 7) (ELOVL FA elongase 7) (Elongation of very long chain fatty acids protein 7) (Very long chain 3-ketoacyl-CoA synthase 7) (Very long chain 3-oxoacyl-CoA synthase 7)',
 'A1L4H1': 'Soluble scavenger receptor cysteine-rich domain-containing protein SSC5D (Soluble scavenger protein with 5 SRCR domains) (SSc5D)',
 'A1L4K1': 'Fibronectin type III and SPRY domain-containing protein 2 (SPRY domain-containing protein 1)',
 'A1X283': 'SH3 and PX domain-containing protein 2B (Adapter protein HOFI) (Factor for adipocyte differentiation 49) (Tyrosine kinase substrate with four SH3 domains)',
 'A1XBS5': 'CBY1-interacting BAR domain-containing protein 1',
 'A1Z1Q3': 'ADP-ribose glycohydrolase MACROD2 (MACRO domain-containing protein 2) (O-acetyl-ADP-ribose deacetylase MACROD2) (EC 3.5.1.-) ([Protein ADP-ribosylaspartate] hydrolase MACROD2) (EC 3.2.2.-) ([Protein ADP-ribosylglutamate] hydrolase MACROD2) (EC 3.2.2.-)',
 'A2A288': 'Probable ribonuclease ZC3H12D (EC 3.1.-.-) (MCP-induced protein 4) (Transformed follicular lymphoma) (Zinc finger CCCH domain-containing protein 12D) (p34)',
 'A2A2Y4': 'FERM domain-containing protein 3 (Band 4.1-like protein 4O) (Ovary type protein 4.1) (4.1O)',
 'A2BDE7': 'PHLDA1 protein',
 'A2I2P0': 'Cryptochrome-1',
 'A2IDD5': 'Coiled-coil domain-containing protein 78 (hsCCDC78)',
 'A2PYH4': 'Probable ATP-dependent DNA helicase HFM1 (EC 3.6.4.12) (SEC63 domain-containing protein 1)',
 'A2RRP1': 'NBAS subunit of NRZ tethering complex (Neuroblastoma-amplified gene protein) (Neuroblastoma-amplified sequence)',
 'A2RTX5': 'Threonine--tRNA ligase 2, cytoplasmic (EC 6.1.1.3) (Threonyl-tRNA synthetase) (ThrRS) (Threonyl-tRNA synthetase protein 3)',
 'A2RU14': 'Transmembrane protein 218',
 'A2RU30': 'Protein TESPA1 (Thymocyte-expressed positive selection-associated protein 1)',
 'A2RU49': 'Hydroxylysine kinase (5-hydroxy-L-lysine kinase) (EC 2.7.1.81) (Aminoglycoside phosphotransferase domain-containing protein 1)',
 'A2RUB1': 'Meiosis-specific coiled-coil domain-containing protein MEIOC (Meiosis-specific with coiled-coil domain protein)',
 'A2RUB6': 'Coiled-coil domain-containing protein 66',
 'A2RUC4': 'tRNA wybutosine-synthesizing protein 5 (hTYW5) (tRNA yW-synthesizing protein 5) (EC 1.14.11.42) (tRNA(Phe) (7-(3-amino-3-carboxypropyl)wyosine(37)-C(2))-hydroxylase)',
 'A2RUH7': 'Myosin-binding protein H-like',
 'A2VDJ0': 'Transmembrane protein 131-like',
 'A2VEC9': 'SCO-spondin (SCO-spondin pseudogene)',
 'A3KMH1': 'von Willebrand factor A domain-containing protein 8 (PEX7-binding protein 2) (P7BP2)',
 'A3QNQ0': 'TGF-beta receptor type-2 (TGFR-2) (EC 2.7.11.30) (TGF-beta type II receptor) (Transforming growth factor-beta receptor type II)',
 'A4D0S4': 'Laminin subunit beta-4 (Laminin beta-1-related protein)',
 'A4D0Y8': 'Leptin (Obesity factor)',
 'A4D126': 'D-ribitol-5-phosphate cytidylyltransferase (EC 2.7.7.40) (2-C-methyl-D-erythritol 4-phosphate cytidylyltransferase-like protein) (Isoprenoid synthase domain-containing protein) (hISPD)',
 'A4D161': 'Protein FAM221A',
 'A4D1B1': 'Platelet glycoprotein 4 (Glycoprotein IIIb) (PAS IV) (PAS-4) (Platelet glycoprotein IV)',
 'A4D1B5': 'Gamma-secretase-activating protein (GSAP) (Protein pigeon homolog) [Cleaved into: Gamma-secretase-activating protein 16 kDa C-terminal form (GSAP-16K)]',
 'A4D1E9': 'GTP-binding protein 10 (Protein obg homolog 2) (ObgH2)',
 'A4D1P6': 'WD repeat-containing protein 91',
 'A4D1T9': 'Probable inactive serine protease 37 (Probable inactive trypsin-X2)',
 'A4D1U5': 'Acylglycerol kinase, mitochondrial (EC 2.7.1.107) (EC 2.7.1.138) (EC 2.7.1.94) (Multiple substrate lipid kinase)',
 'A4D1W7': 'Inhibin beta A chain (Activin beta-A chain)',
 'A4D256': 'Dual specificity protein phosphatase CDC14C (EC 3.1.3.16) (EC 3.1.3.48) (CDC14 cell division cycle 14 homolog C)',
 'A4D2B0': 'Metallo-beta-lactamase domain-containing protein 1 (EC 3.1.27.-) (Endoribonuclease MBLAC1)',
 'A4D2B8': 'Putative postmeiotic segregation increased 2-like protein 1 (PMS2-related protein 2) (Postmeiotic segregation increased 2-like protein 13) (Postmeiotic segregation increased 2-like protein 6) (Postmeiotic segregation increased 2-like protein 8) (Postmeiotic segregation increased protein 3) (hPMS3) (Postmeiotic segregation increased protein 8) (Putative postmeiotic segregation increased 2 pseudogene 1)',
 'A4F3V8': 'Cytochrome P450 1A (EC 1.14.14.1)',
 'A4F4K3': 'Cytochrome P450 1A (EC 1.14.14.1)',
 'A4F4K4': 'Cytochrome P450 1A (EC 1.14.14.1)',
 'A4GXA9': 'Probable crossover junction endonuclease EME2 (EC 3.1.22.-)',
 'A4LAA3': 'Transcriptional regulator ATRX (EC 3.6.4.12) (ATP-dependent helicase ATRX) (X-linked nuclear protein)',
 'A4QPA9': 'Dual specificity mitogen-activated protein kinase kinase 1 (EC 2.7.12.2) (ERK activator kinase 1) (MAPK/ERK kinase 1)',
 'A4UGR9': 'Xin actin-binding repeat-containing protein 2 (Beta-xin) (Cardiomyopathy-associated protein 3) (Xeplin)',
 'A5A3E0': 'POTE ankyrin domain family member F (ANKRD26-like family C member 1B) (Chimeric POTE-actin protein)',
 'A5D8T8': 'C-type lectin domain family 18 member A (Mannose receptor-like protein 2)',
 'A5D8V6': 'Vacuolar protein sorting-associated protein 37C (hVps37C) (ESCRT-I complex subunit VPS37C)',
 'A5D8V7': 'Outer dynein arm-docking complex subunit 3 (Coiled-coil domain-containing protein 151)',
 'A5D8W1': 'Cilia- and flagella-associated protein 69',
 'A5LHX3': 'Proteasome subunit beta type-11 (EC 3.4.25.1) (Proteasome subunit beta-5t)',
 'A5PKW4': 'PH and SEC7 domain-containing protein 1 (Exchange factor for ADP-ribosylation factor guanine nucleotide factor 6) (Exchange factor for ARF6) (Exchange factor for ARF6 A) (Pleckstrin homology and SEC7 domain-containing protein 1)',
 'A5PLL7': 'Plasmanylethanolamine desaturase 1 (EC 1.14.19.77) (Transmembrane protein 189)',
 'A5X5Y0': '5-hydroxytryptamine receptor 3E (5-HT3-E) (5-HT3E) (Serotonin receptor 3E)',
 'A5YKK6': 'CCR4-NOT transcription complex subunit 1 (CCR4-associated factor 1) (Negative regulator of transcription subunit 1 homolog) (NOT1H) (hNOT1)',
 'A5YM40': 'Transforming growth factor beta',
 'A5YM72': 'Carnosine synthase 1 (EC 6.3.2.11) (ATP-grasp domain-containing protein 1)',
 'A6BM72': 'Multiple epidermal growth factor-like domains protein 11 (Multiple EGF-like domains protein 11)',
 'A6H8L5': 'Hepatic triacylglycerol lipase (EC 3.1.1.3) (EC 3.1.1.32) (EC 3.1.1.5) (Lipase member C) (Lysophospholipase) (Phospholipase A1)',
 'A6H8Y1': "Transcription factor TFIIIB component B'' homolog (Transcription factor IIIB 150) (TFIIIB150) (Transcription factor-like nuclear regulator)",
 'A6H8Z2': 'Protein FAM221B',
 'A6NC98': 'Coiled-coil domain-containing protein 88B (Brain leucine zipper domain-containing protein) (Gipie) (Hook-related protein 3) (HkRP3)',
 'A6NCS4': 'Homeobox protein Nkx-2.6 (Homeobox protein NK-2 homolog F)',

In [187]:
# Create a dictionary where all the parenthetical expressions in the protein names are stripped out
# Also remove double spaces

uniprot_to_name_stripped = {k:re.sub(r'\(.*?\)', '', v) for k, v in uniprot_to_name_map.items()}
uniprot_to_name_stripped = {k:re.sub(r'\s+', ' ', v).strip() for k, v in uniprot_to_name_stripped.items()}

In [189]:
# Create dictionary with protein names as keys

name_to_protein = {}

for protein_id, prot_name in uniprot_to_name_stripped.items():
    if isinstance(prot_name, float) and math.isnan(prot_name):  
        prot_name = f"NaN_{protein_id}"
    if prot_name not in name_to_protein:
        name_to_protein[prot_name] = []
    name_to_protein[prot_name].append(protein_id)

In [192]:
{k:v for k,v in name_to_protein.items() if k.startswith('Protein-L-isoaspartate')}

{'Protein-L-isoaspartate O-methyltransferase': ['P22061',
  'F6S8N6',
  'A0A384MDK7',
  'A0A3F2YNX8',
  'B7Z972',
  'C9J0F2',
  'F8WAV5',
  'F8WAX2',
  'F8WDT3',
  'H7C4X2'],
 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 1': ['Q96MG8',
  'B4E2B4',
  'E5RGG7',
  'H0YBU4',
  'Q658R8'],
 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 2': ['Q9NV79'],
 'Protein-L-isoaspartate O-methyltransferase domain containing 2': ['A0A0G2JM70',
  'A0A0G2JR02',
  'F8W9F3',
  'V9GYG6',
  'V9GYL1',
  'V9GYZ4',
  'V9GYZ7',
  'V9GZ41']}

In [67]:
# Create dictionaries corresponding uniprot ID to reviewed and annotation status

uniprot_id_to_reviewed = {u:r for u, r in zip(list(uniprot_ids['Entry']), list(uniprot_ids['Reviewed']))}

uniprot_id_to_annotation = {u:r for u, r in zip(list(uniprot_ids['Entry']), list(uniprot_ids['Annotation']))}

In [68]:
# Choose preferred Uniprot ID among different IDs that refer to the same protein

protein_to_preferred_id = {}

for prot_name, protein_ids in name_to_protein.items():
    prot_dict = {id:[uniprot_id_to_reviewed[id], uniprot_id_to_annotation[id]] for id in protein_ids}
    
    preferred_id = None
    highest_status = 'unreviewed'
    highest_score = -1

    for id, (status, score) in prot_dict.items():
        update = False
        if preferred_id is None:
            update = True
        elif highest_status == 'unreviewed' and status == 'reviewed':
            update = True
        elif highest_status == 'reviewed' and status == 'unreviewed':
            update = False
        # Review status is equal at this point
        elif highest_score > score:
            update = True
        elif highest_score == score and len(id) < len(preferred_id):
            update = True
        else:
            update = False
        
        if update:
            preferred_id = id
            highest_status = status
            highest_score = score

    for prot_id in prot_dict:
        protein_to_preferred_id[prot_id] = preferred_id

In [69]:
# Map ENSP IDs to their preferred uniprot ID

ensp_to_pref_uniprot = {e:protein_to_preferred_id[u] for e, u in ensp_to_uniprot.items()}

In [70]:
ensp_to_pref_uniprot

{'ENSP00000264335': 'P62258',
 'ENSP00000461762': 'P62258',
 'ENSP00000481059': 'P62258',
 'ENSP00000487356': 'P62258',
 'ENSP00000248975': 'Q04917',
 'ENSP00000306330': 'P61981',
 'ENSP00000340989': 'P31947',
 'ENSP00000238081': 'P27348',
 'ENSP00000371267': 'P27348',
 'ENSP00000309503': 'P63104',
 'ENSP00000379281': 'P63104',
 'ENSP00000379283': 'P63104',
 'ENSP00000379286': 'P63104',
 'ENSP00000379287': 'P63104',
 'ENSP00000379288': 'P63104',
 'ENSP00000395114': 'P63104',
 'ENSP00000398599': 'P63104',
 'ENSP00000430072': 'P63104',
 'ENSP00000263776': 'Q96QU6',
 'ENSP00000368109': 'Q4AC99',
 'ENSP00000261461': 'Q15172',
 'ENSP00000442866': 'Q15172',
 'ENSP00000164133': 'Q15173',
 'ENSP00000377669': 'Q14738',
 'ENSP00000420674': 'Q14738',
 'ENSP00000417963': 'Q14738',
 'ENSP00000337641': 'Q16537',
 'ENSP00000404632': 'Q16537',
 'ENSP00000452396': 'Q16537',
 'ENSP00000329009': 'Q13362',
 'ENSP00000333905': 'Q13362',
 'ENSP00000262239': 'Q13362',
 'ENSP00000412324': 'Q13362',
 'ENSP00000408389': 'Q13362',
 'ENSP00000324804': 'P30153',
 'ENSP00000311344': 'P30154',
 'ENSP00000343317': 'P30154',
 'ENSP00000376775': 'P30154',
 'ENSP00000410671': 'P30154',
 'ENSP00000437193': 'P30154',
 'ENSP00000325074': 'P63151',
 'ENSP00000370113': 'P63151',
 'ENSP00000336591': 'Q00005',
 'ENSP00000377931': 'Q00005',
 'ENSP00000377933': 'Q00005',
 'ENSP00000377935': 'Q00005',
 'ENSP00000377936': 'Q00005',
 'ENSP00000398779': 'Q00005',
 'ENSP00000421396': 'Q00005',
 'ENSP00000431320': 'Q00005',
 'ENSP00000399970': 'Q66LE6',
 'ENSP00000335083': 'Q9Y2T4',
 'ENSP00000372042': 'Q9Y2T4',
 'ENSP00000423649': 'Q9Y2T4',
 'ENSP00000425247': 'Q9Y2T4',
 'ENSP00000422374': 'Q9Y2T4',
 'ENSP00000358421': 'P14060',
 'ENSP00000432268': 'P14060',
 'ENSP00000358424': 'P26439',
 'ENSP00000445122': 'P26439',
 'ENSP00000262520': 'Q9H2F3',
 'ENSP00000297679': 'Q9H2F3',
 'ENSP00000411979': 'Q9Y3L3',
 'ENSP00000497104': 'Q9Y3L3',
 'ENSP00000403231': 'P78314',
 'ENSP00000425537': 'D6R995',
 'ENSP00000422796': 'D6R995',
 'ENSP00000422168': 'P78314',
 'ENSP00000423275': 'D6R995',
 'ENSP00000424917': 'D6R995',
 'ENSP00000424846': 'P78314',
 'ENSP00000424105': 'D6R995',
 'ENSP00000424072': 'P78314',
 'ENSP00000423823': 'D6R995',
 'ENSP00000355428': 'Q7L8J4',
 'ENSP00000373301': 'O60239',
 'ENSP00000386231': 'O60239',
 'ENSP00000388553': 'O60239',
 'ENSP00000294973': 'P46952',
 'ENSP00000265395': 'P31937',
 'ENSP00000219431': 'P29372',
 'ENSP00000348809': 'P29372',
 'ENSP00000380918': 'P29372',
 'ENSP00000340691': 'Q13541',
 'ENSP00000362314': 'Q13542',
 'ENSP00000308472': 'O60516',
 'ENSP00000328103': 'Q9NRA8',
 'ENSP00000342927': 'Q9NRA8',
 'ENSP00000380659': 'Q9NRA8',
 'ENSP00000340815': 'P08195',
 'ENSP00000367121': 'P08195',
 'ENSP00000367122': 'P08195',
 'ENSP00000367123': 'P08195',
 'ENSP00000440001': 'F5H867',
 'ENSP00000442135': 'F5H867',
 'ENSP00000506006': 'P08195',
 'ENSP00000505110': 'P08195',
 'ENSP00000316244': 'P08908',
 'ENSP00000358963': 'P28222',
 'ENSP00000363748': 'P28221',
 'ENSP00000307766': 'P28566',
 'ENSP00000322924': 'P30939',
 'ENSP00000437737': 'P28223',
 'ENSP00000258400': 'P41595',
 'ENSP00000276198': 'P28335',
 'ENSP00000361018': 'P28335',
 'ENSP00000361019': 'P28335',
 'ENSP00000299961': 'P46098',
 'ENSP00000347754': 'P46098',
 'ENSP00000364648': 'P46098',
 'ENSP00000424189': 'P46098',
 'ENSP00000424776': 'P46098',
 'ENSP00000260191': 'O95264',
 'ENSP00000443118': 'O95264',
 'ENSP00000322617': 'Q8WXA8',
 'ENSP00000371929': 'Q70Z44',
 'ENSP00000405409': 'Q70Z44',
 'ENSP00000389268': 'Q70Z44',
 'ENSP00000335511': 'A5X5Y0',
 'ENSP00000401444': 'A5X5Y0',
 'ENSP00000401900': 'A5X5Y0',
 'ENSP00000395833': 'A5X5Y0',
 'ENSP00000406050': 'A5X5Y0',
 'ENSP00000353915': 'Q13639',
 'ENSP00000367120': 'Q13639',
 'ENSP00000435904': 'Q13639',
 'ENSP00000427913': 'Q13639',
 'ENSP00000428320': 'Q13639',
 'ENSP00000430979': 'Q13639',
 'ENSP00000430874': 'Q13639',
 'ENSP00000287907': 'P47898',
 'ENSP00000289753': 'P50406',
 'ENSP00000277874': 'P34969',
 'ENSP00000337949': 'P34969',
 'ENSP00000360784': 'P34969',
 'ENSP00000258761': 'Q9Y6E2',
 'ENSP00000397249': 'Q9Y6E2',
 'ENSP00000386837': 'Q7L1Q6',
 'ENSP00000386474': 'Q7L1Q6',
 'ENSP00000394316': 'Q7L1Q6',
 'ENSP00000235628': 'Q9BXI3',
 'ENSP00000305979': 'Q96P26',
 'ENSP00000352904': 'Q96P26',
 'ENSP00000387166': 'Q9H0P0',
 'ENSP00000496364': 'Q9H0P0',
 'ENSP00000389948': 'Q969T7',
 'ENSP00000339479': 'P49902',
 'ENSP00000383960': 'P49902',
 'ENSP00000502679': 'P49902',
 'ENSP00000502205': 'P49902',
 'ENSP00000502215': 'P49902',
 'ENSP00000501689': 'P49902',
 'ENSP00000502801': 'P49902',
 'ENSP00000257770': 'P21589',
 'ENSP00000358665': 'P21589',
 'ENSP00000270776': 'P52209',
 'ENSP00000252603': 'O95336',
 'ENSP00000300175': 'P05408',
 'ENSP00000388560': 'P05408',
 'ENSP00000482615': 'P05408',
 'ENSP00000488109': 'P05408',
 'ENSP00000488509': 'P05408',
 'ENSP00000343439': 'P36639',
 'ENSP00000339503': 'P36639',
 'ENSP00000349148': 'P36639',
 'ENSP00000380239': 'P36639',
 'ENSP00000380241': 'P36639',
 'ENSP00000380242': 'P36639',
 'ENSP00000472409': 'P0DKL9',
 'ENSP00000510304': 'P0DKL9',
 'ENSP00000293350': 'Q8IZ83',
 'ENSP00000410142': 'Q8IZ83',
 'ENSP00000318259': 'Q676U5',
 'ENSP00000362625': 'Q676U5',
 'ENSP00000375872': 'Q676U5',
 'ENSP00000375875': 'Q676U5',
 'ENSP00000487542': 'Q676U5',
 'ENSP00000487298': 'Q676U5',
 'ENSP00000487446': 'Q676U5',
 'ENSP00000487455': 'Q676U5',
 'ENSP00000326340': 'Q8NAA4',
 'ENSP00000259396': 'P02763',
 'ENSP00000394936': 'P19652',
 'ENSP00000477957': 'P20848',
 'ENSP00000348068': 'P01009',
 'ENSP00000376802': 'P01009',
 'ENSP00000376803': 'P01009',
 'ENSP00000386094': 'P01009',
 'ENSP00000385960': 'P01009',
 'ENSP00000408474': 'P01009',
 'ENSP00000390299': 'P01009',
 'ENSP00000416066': 'P01009',
 'ENSP00000416354': 'P01009',
 'ENSP00000451525': 'P01009',
 'ENSP00000490054': 'P01009',
 'ENSP00000263100': 'P04217',
 'ENSP00000363105': 'Q9NQ94',
 'ENSP00000363107': 'Q9NQ94',
 'ENSP00000363109': 'Q9NQ94',
 'ENSP00000363113': 'Q9NQ94',
 'ENSP00000378873': 'Q9NQ94',
 'ENSP00000397953': 'F8W9F8',
 'nan': 'Q69YV8',
 'ENSP00000477695': 'Q5TYW2',
 'ENSP00000321853': 'P08697',
 'ENSP00000371493': 'P08697',
 'ENSP00000403877': 'P08697',
 'ENSP00000402286': 'C9JMH6',
 'ENSP00000479005': 'P08697',
 'ENSP00000481874': 'P08697',
 'ENSP00000302621': 'P02750',
 'ENSP00000323929': 'P01023',
 'ENSP00000299698': 'A8K2U0',
 'ENSP00000438292': 'A8K2U0',
 'ENSP00000295181': 'A7E2S9',
 'ENSP00000386398': 'A7E2S9',
 'ENSP00000475261': 'U3KPV4',
 'ENSP00000249005': 'Q9NPC4',
 'ENSP00000370678': 'Q9NPC4',
 'ENSP00000384794': 'Q9NPC4',
 'ENSP00000494127': 'Q9NPC4',
 'ENSP00000236709': 'Q9UNA3',
 'ENSP00000284981': 'P05067',
 'ENSP00000345463': 'P05067',
 'ENSP00000346129': 'P05067',
 'ENSP00000350578': 'P05067',
 'ENSP00000351796': 'P05067',
 'ENSP00000387483': 'P05067',
 'ENSP00000430000': 'Q96GX2',
 'ENSP00000308549': 'P30542',
 'ENSP00000338435': 'P30542',
 'ENSP00000356204': 'P30542',
 'ENSP00000356205': 'P30542',
 'ENSP00000336630': 'P29274',
 'ENSP00000480012': 'P29274',
 'ENSP00000483102': 'P29274',
 'ENSP00000481552': 'P29274',
 'ENSP00000304501': 'P29275',
 'ENSP00000241356': 'P0DMS8',
 'ENSP00000253188': 'Q9NS82',
 'ENSP00000232892': 'P22760',
 'ENSP00000209873': 'Q9NRG9',
 'ENSP00000377908': 'Q9NRG9',
 'ENSP00000517437': 'Q9NRG9',
 'ENSP00000517438': 'Q9NRG9',
 'ENSP00000397924': 'Q15758',
 'ENSP00000406532': 'Q15758',
 'ENSP00000444408': 'Q15758',
 'ENSP00000468890': 'B3KSM4',
 'ENSP00000471626': 'M0R144',
 'ENSP00000519244': 'Q15758',
 'ENSP00000324842': 'Q86V21',
 'ENSP00000376793': 'P01011',
 'ENSP00000376795': 'P01011',
 'ENSP00000450540': 'P01011',
 'ENSP00000452476': 'P01011',
 'ENSP00000336808': 'Q8N5Z0',
 'ENSP00000226840': 'Q8N5Z0',
 'ENSP00000423190': 'Q8N5Z0',
 'ENSP00000423341': 'Q8N5Z0',
 'ENSP00000261880': 'Q6PD74',
 'ENSP00000440735': 'Q6PD74',
 'ENSP00000453263': 'Q6PD74',
 'ENSP00000385181': 'Q2M2I8',
 'ENSP00000386456': 'Q2M2I8',
 'ENSP00000229328': 'Q9Y478',
 'ENSP00000441369': 'Q9Y478',
 'ENSP00000254101': 'O43741',
 'ENSP00000323867': 'P54619',
 'ENSP00000447433': 'P54619',
 'ENSP00000448972': 'P54619',
 'ENSP00000287878': 'Q9UGJ0',
 'ENSP00000376549': 'Q9UGJ0',
 'ENSP00000387386': 'Q9UGJ0',
 'ENSP00000419493': 'Q9UGJ0',
 'ENSP00000499103': 'Q9UGJ0',
 'ENSP00000498796': 'Q9UGJ0',
 'ENSP00000499025': 'Q9UGJ0',
 'ENSP00000397133': 'Q9UGI9',
 'ENSP00000436068': 'Q9UGI9',
 'ENSP00000377078': 'Q9H7C9',
 'ENSP00000432830': 'E9PNP3',
 'ENSP00000431808': 'Q9H7C9',
 'ENSP00000433293': 'Q9H7C9',
 'ENSP00000248450': 'Q13685',
 'ENSP00000346148': 'Q13131',
 'ENSP00000380317': 'Q13131',
 'ENSP00000360290': 'P54646',
 'ENSP00000313674': 'Q9Y312',
 'ENSP00000363043': 'Q9Y312',
 'ENSP00000506354': 'Q9Y312',
 'ENSP00000505295': 'Q9Y312',
 'ENSP00000505405': 'Q9Y312',
 'ENSP00000506185': 'Q9Y312',
 'ENSP00000505061': 'Q9Y312',
 'ENSP00000367528': 'Q4LEZ3',
 'ENSP00000353355': 'Q9BTE6',
 'ENSP00000400870': 'Q9BTE6',
 'ENSP00000377040': 'Q9UDR5',
 'ENSP00000403768': 'Q9UDR5',
 'ENSP00000505381': 'Q9UDR5',
 'ENSP00000505958': 'Q9UDR5',
 'ENSP00000303077': 'Q8NHS2',
 'ENSP00000359539': 'P17174',
 'ENSP00000477848': 'Q9NY61',
 'ENSP00000481894': 'Q9NY61',
 'ENSP00000245206': 'P00505',
 'ENSP00000394100': 'P00505',
 'ENSP00000336693': 'Q7Z5M8',
 'ENSP00000343951': 'Q7Z5M8',
 'ENSP00000371460': 'Q7Z5M8',
 'ENSP00000450643': 'Q7Z5M8',
 'ENSP00000250974': 'Q96GS6',
 'ENSP00000292577': 'Q96GS6',
 'ENSP00000504042': 'Q96GS6',
 'ENSP00000330222': 'Q5VST6',
 'ENSP00000366240': 'Q5VST6',
 'ENSP00000258884': 'Q6PCB6',
 'ENSP00000452778': 'Q6PCB6',
 'ENSP00000349237': 'Q7Z5R6',
 'ENSP00000365411': 'Q7Z5R6',
 'ENSP00000249116': 'P31941',
 'ENSP00000384359': 'P31941',
 'ENSP00000461288': 'P31941',
 'ENSP00000485234': 'P31941',
 'ENSP00000327459': 'Q9UH17',
 'ENSP00000338897': 'Q9UH17',
 'ENSP00000385068': 'Q9UH17',
 'ENSP00000355340': 'Q9NRW3',
 'ENSP00000216099': 'Q96AK3',
 'ENSP00000309749': 'Q8IUX4',
 'ENSP00000370977': 'Q8IUX4',
 'ENSP00000385057': 'Q9HC16',
 'ENSP00000216123': 'Q6NTF7',
 'ENSP00000385741': 'Q6NTF7',
 'ENSP00000411754': 'Q6NTF7',
 'ENSP00000483689': 'Q6NTF7',
 'ENSP00000363868': 'O95477',
 'ENSP00000344155': 'Q9BZC7',
 'ENSP00000360666': 'Q9BZC7',
 'ENSP00000481105': 'A0A087WXK5',
 'ENSP00000301732': 'Q99758',
 'ENSP00000454397': 'Q99758',
 'ENSP00000359245': 'P78363',
 'ENSP00000376443': 'Q8WWZ7',
 'ENSP00000467882': 'Q8WWZ7',
 'ENSP00000284425': 'Q8N139',
 'ENSP00000466862': 'Q8N139',
 'ENSP00000263094': 'Q8IZY2',
 'ENSP00000269080': 'O94911',
 'ENSP00000467271': 'O94911',
 'ENSP00000342216': 'Q8IUA7',
 'ENSP00000465601': 'Q8IUA7',
 'ENSP00000269081': 'Q8WWZ4',
 'ENSP00000429853': 'Q8WWZ4',
 'ENSP00000429945': 'Q8WWZ4',
 'ENSP00000509702': 'Q8WWZ4',
 'ENSP00000272895': 'Q86UK0',
 'ENSP00000374312': 'Q86UK0',
 'ENSP00000409268': 'Q86UQ4',
 'ENSP00000258738': 'Q2M3G0',
 'ENSP00000384881': 'Q2M3G0',
 'ENSP00000383899': 'Q2M3G0',
 'ENSP00000406730': 'Q2M3G0',
 'ENSP00000265316': 'Q9NP58',
 'ENSP00000295750': 'Q9NP58',
 'ENSP00000253577': 'O75027',
 'ENSP00000343849': 'O75027',
 'ENSP00000362492': 'O75027',
 'ENSP00000280560': 'Q9NP78',
 'ENSP00000456813': 'Q9NP78',
 'ENSP00000280559': 'Q9NP78',
 'ENSP00000376234': 'Q9NP78',
 'ENSP00000456375': 'Q9NP78',
 'ENSP00000441734': 'Q9NP78',
 'ENSP00000440288': 'Q9NP78',
 'ENSP00000355637': 'Q9NRK6',
 'ENSP00000497931': 'O95342',
 'ENSP00000303960': 'Q09428',
 'ENSP00000374467': 'Q09428',
 'ENSP00000495532': 'Q09428',
 'ENSP00000507005': 'Q09428',
 'ENSP00000261200': 'O60706',
 'ENSP00000261201': 'O60706',
 'ENSP00000218104': 'P33897',
 'ENSP00000310688': 'Q9UBJ2',
 'ENSP00000326880': 'P28288',
 'ENSP00000359233': 'P28288',
 'ENSP00000349396': 'O14678',
 'ENSP00000296577': 'P61221',
 'ENSP00000313603': 'Q8NE71',
 'ENSP00000365728': 'Q8NE71',
 'ENSP00000373081': 'Q8NE71',
 'ENSP00000373082': 'Q8NE71',
 'ENSP00000404726': 'Q8NE71',
 'ENSP00000389065': 'Q8NE71',
 'ENSP00000391102': 'Q8NE71',
 'ENSP00000393143': 'Q8NE71',
 'ENSP00000411327': 'Q8NE71',
 'ENSP00000414373': 'Q8NE71',
 'ENSP00000403526': 'Q8NE71',
 'ENSP00000389472': 'Q8NE71',
 'ENSP00000412553': 'Q8NE71',
 'ENSP00000413319': 'Q8NE71',
 'ENSP00000287844': 'Q9UG63',
 'ENSP00000292808': 'Q9NUQ8',
 'ENSP00000411471': 'Q9NUQ8',
 'ENSP00000339744': 'P45844',
 'ENSP00000291524': 'P45844',
 'ENSP00000354995': 'P45844',
 'ENSP00000381467': 'P45844',
 'ENSP00000381475': 'P45844',
 'ENSP00000237612': 'Q9UNQ0',
 'ENSP00000426917': 'Q9UNQ0',
 'ENSP00000498246': 'Q9UNQ0',
 'ENSP00000479253': 'Q9H172',
 'ENSP00000481728': 'Q9H172',
 'ENSP00000484289': 'Q9H172',
 'ENSP00000384513': 'Q9H222',
 'ENSP00000272286': 'Q9H221',
 'ENSP00000341408': 'Q8N2K0',
 'ENSP00000365725': 'Q8N2K0',
 'ENSP00000397229': 'Q0P651',
 'ENSP00000229304': 'P41238',
 'ENSP00000244669': 'Q9Y235',
 'ENSP00000310622': 'Q8WW27',
 'ENSP00000302657': 'Q6UXT9',
 'ENSP00000326491': 'Q96SE0',
 'ENSP00000410756': 'Q96SE0',
 'ENSP00000481238': 'Q96SE0',
 'ENSP00000268129': 'P08910',
 'ENSP00000455639': 'P08910',
 'ENSP00000289119': 'Q8WU67',
 'ENSP00000463365': 'Q8WU67',
 'ENSP00000388751': 'Q8TB40',
 'ENSP00000414558': 'Q8TB40',
 'ENSP00000495778': 'Q8WTS1',
 'ENSP00000497701': 'Q8WTS1',
 'ENSP00000295962': 'Q9BV23',
 'ENSP00000420315': 'Q9BV23',
 'ENSP00000247706': 'Q96I13',
 'ENSP00000273359': 'Q9NUJ1',
 'ENSP00000418973': 'Q9NUJ1',
 'ENSP00000222800': 'Q8NFV4',
 'ENSP00000392945': 'Q8NFV4',
 'ENSP00000378579': 'Q8NFV4',
 'ENSP00000416970': 'Q8NFV4',
 'ENSP00000365063': 'Q7L211',
 'ENSP00000273596': 'Q9BUJ0',
 'ENSP00000354841': 'Q96IU4',
 'ENSP00000378455': 'Q96IU4',
 'ENSP00000420065': 'Q96IU4',
 'ENSP00000433388': 'Q96IU4',
 'ENSP00000379282': 'O95870',
 'ENSP00000410347': 'O95870',
 'ENSP00000395665': 'O95870',
 'ENSP00000448431': 'O95870',
 'ENSP00000447549': 'O95870',
 'ENSP00000447846': 'O95870',
 'ENSP00000447498': 'O95870',
 'ENSP00000449579': 'O95870',
 'ENSP00000448451': 'O95870',
 'ENSP00000358932': 'Q9H3Z7',
 'ENSP00000279599': 'Q8IZP0',
 'ENSP00000352114': 'Q8IZP0',
 'ENSP00000365307': 'Q8IZP0',
 'ENSP00000365308': 'Q8IZP0',
 'ENSP00000365309': 'Q8IZP0',
 'ENSP00000365310': 'Q8IZP0',
 'ENSP00000365312': 'Q8IZP0',
 'ENSP00000365336': 'Q8IZP0',
 'ENSP00000365340': 'Q8IZP0',
 'ENSP00000440101': 'Q8IZP0',
 'ENSP00000261017': 'Q9NYB9',
 'ENSP00000225941': 'Q9P2A4',
 'ENSP00000406651': 'Q9P2A4',
 'ENSP00000363753': 'Q9NX38',
 'ENSP00000323315': 'P00519',
 'ENSP00000361423': 'P00519',
 'ENSP00000339209': 'P42684',
 'ENSP00000356595': 'P42684',
 'ENSP00000427562': 'P42684',
 'ENSP00000426831': 'P42684',
 'ENSP00000423413': 'P42684',
 'ENSP00000424697': 'P42684',
 'ENSP00000423578': 'P42684',
 'ENSP00000358257': 'O14639',
 'ENSP00000358260': 'O14639',
 'ENSP00000376679': 'O14639',
 'ENSP00000376682': 'O14639',
 'ENSP00000433629': 'F8W8M4',
 'ENSP00000342813': 'Q6H8Q1',
 'ENSP00000355003': 'Q6H8Q1',
 'ENSP00000354887': 'Q6H8Q1',
 'ENSP00000384658': 'Q6H8Q1',
 'ENSP00000389410': 'Q6H8Q1',
 'ENSP00000393511': 'Q6H8Q1',
 'ENSP00000421283': 'Q6H8Q1',
 'ENSP00000423661': 'Q6H8Q1',
 'ENSP00000310309': 'O94929',
 'ENSP00000315841': 'O94929',
 'ENSP00000421183': 'O94929',
 'ENSP00000425394': 'O94929',
 'ENSP00000430150': 'O94929',
 'ENSP00000356632': 'Q9P1F3',
 'ENSP00000311436': 'Q8N0Z2',
 'ENSP00000369857': 'Q6UWZ7',
 'ENSP00000298492': 'Q15018',
 'ENSP00000291107': 'Q12979',
 'ENSP00000303909': 'Q12979',
 'ENSP00000445198': 'Q12979',
 'ENSP00000442048': 'Q12979',
 'ENSP00000484030': 'Q12979',
 'ENSP00000483168': 'Q12979',
 'ENSP00000481740': 'Q12979',
 'ENSP00000479455': 'Q12979',
 'ENSP00000478880': 'Q12979',
 'ENSP00000486511': 'Q12979',
 'ENSP00000486214': 'Q12979',
 'ENSP00000274849': 'Q9ULW3',
 'ENSP00000517947': 'Q9ULW3',
 'ENSP00000232744': 'Q969K4',
 'ENSP00000412684': 'Q969K4',
 'ENSP00000417366': 'Q969K4',
 'ENSP00000410157': 'Q8N961',
 'ENSP00000280758': 'A6QL63',
 'ENSP00000349690': 'A6QL63',
 'ENSP00000413889': 'A6QL63',
 'ENSP00000447319': 'A6QL63',
 'ENSP00000448322': 'A6QL63',
 'ENSP00000479901': 'Q13085',
 'ENSP00000482269': 'Q13085',
 'ENSP00000483674': 'Q13085',
 'ENSP00000478547': 'Q13085',
 'ENSP00000483300': 'Q13085',
 'ENSP00000482368': 'Q13085',
 'ENSP00000478577': 'Q13085',
 'ENSP00000480031': 'Q13085',
 'ENSP00000341044': 'O00763',
 'ENSP00000367079': 'O00763',
 'ENSP00000281182': 'Q9UKU7',
 'ENSP00000363884': 'Q9UKU7',
 'ENSP00000312618': 'Q9H845',
 'ENSP00000506340': 'Q9H845',
 'ENSP00000233710': 'P28330',
 'ENSP00000359878': 'P11310',
 'ENSP00000409612': 'P11310',
 'ENSP00000242592': 'P16219',
 'ENSP00000344152': 'P49748',
 'ENSP00000349297': 'P49748',
 'ENSP00000438689': 'P49748',
 'ENSP00000158762': 'Q15027',
 'ENSP00000499859': 'Q15027',
 'ENSP00000324287': 'Q15057',
 'ENSP00000321139': 'Q96P50',
 'ENSP00000346733': 'Q96P50',
 'ENSP00000352456': 'O00400',
 'ENSP00000496241': 'O00400',
 'ENSP00000314440': 'Q8NC06',
 'ENSP00000366154': 'Q8NC06',
 'ENSP00000381367': 'Q8NC06',
 'ENSP00000405969': 'Q8NC06',
 'ENSP00000465484': 'Q8NC06',
 'ENSP00000465610': 'Q8NC06',
 'ENSP00000482750': 'Q8NC06',
 'ENSP00000365049': 'Q5T8D3',
 'ENSP00000365066': 'Q5T8D3',
 'ENSP00000365070': 'Q5T8D3',
 'ENSP00000379568': 'Q5T8D3',
 'ENSP00000503631': 'Q5T8D3',
 'ENSP00000356567': 'Q9BR61',
 'ENSP00000495710': 'Q9BR61',
 'ENSP00000367453': 'Q8N6N7',
 'ENSP00000258873': 'Q96GR2',
 'ENSP00000465589': 'Q5FVE4',
 'ENSP00000464938': 'Q5FVE4',
 'ENSP00000466336': 'Q5FVE4',
 'ENSP00000467755': 'Q5FVE4',
 'ENSP00000311117': 'P07108',
 'ENSP00000348116': 'P07108',
 'ENSP00000376815': 'P07108',
 'ENSP00000386486': 'P07108',
 'ENSP00000439012': 'P07108',
 'ENSP00000486281': 'P07108',
 'ENSP00000486361': 'P07108',
 'ENSP00000325137': 'Q6JQN1',
 'ENSP00000389813': 'Q6JQN1',
 'ENSP00000264990': 'Q709F0',
 'ENSP00000357873': 'P45954',
 'ENSP00000357862': 'P45954',
 'ENSP00000219251': 'Q96AP0',
 'ENSP00000478084': 'Q96AP0',
 'ENSP00000252519': 'Q9BYF1',
 'ENSP00000389326': 'Q9BYF1',
 'ENSP00000504747': 'Q9BYF1',
 'ENSP00000504103': 'Q9BYF1',
 'ENSP00000505992': 'Q9BYF1',
 'ENSP00000301452': 'Q8TDN7',
 'ENSP00000342609': 'Q5QJU3',
 'ENSP00000434480': 'Q9NUN7',
 'ENSP00000241069': 'P22303',
 'ENSP00000303211': 'P22303',
 'ENSP00000404865': 'P22303',
 'ENSP00000394976': 'P22303',
 'ENSP00000403474': 'P22303',
 'ENSP00000414858': 'P22303',
 'ENSP00000290863': 'P12821',
 'ENSP00000290866': 'P12821',
 'ENSP00000392247': 'P12821',
 'ENSP00000250699': 'Q9GZZ6',
 'ENSP00000240132': 'Q15822',
 'ENSP00000385026': 'Q15822',
 'ENSP00000315602': 'P32297',
 'ENSP00000267951': 'P32297',
 'ENSP00000452896': 'P32297',
 'ENSP00000359285': 'P43681',
 'ENSP00000299565': 'P30532',
 'ENSP00000276410': 'Q15825',
 'ENSP00000433871': 'Q15825',
 'ENSP00000303727': 'P36544',
 'ENSP00000399087': 'P36544',
 'ENSP00000407546': 'P36544',
 'ENSP00000405989': 'P36544',
 'ENSP00000502560': 'P36544',
 'ENSP00000312663': 'Q9UGM1',
 'ENSP00000261007': 'P02708',
 'ENSP00000261008': 'P02708',
 'ENSP00000357461': 'P17787',
 'ENSP00000289957': 'Q05901',
 'ENSP00000261751': 'P30926',
 'ENSP00000416386': 'P30926',
 'ENSP00000304290': 'P11230',
 'ENSP00000439209': 'P11230',
 'ENSP00000492221': 'P11230',
 'ENSP00000491113': 'P11230',
 'ENSP00000258385': 'Q07001',
 'ENSP00000438380': 'Q07001',
 'ENSP00000497829': 'Q04844',
 'ENSP00000374143': 'P07510',
 'ENSP00000498757': 'P07510',
 'ENSP00000262710': 'Q9UKV3',
 'ENSP00000345541': 'Q9UKV3',
 'ENSP00000350073': 'Q9UKV3',
 'ENSP00000380502': 'Q9UKV3',
 'ENSP00000451328': 'Q9UKV3',
 'ENSP00000329425': 'Q07912',
 'ENSP00000395588': 'Q07912',
 'ENSP00000499858': 'Q07912',
 'ENSP00000420876': 'Q6P4H8',
 'ENSP00000422338': 'Q6P4H8',
 'ENSP00000357103': 'Q16570',
 'ENSP00000357104': 'Q16570',
 'ENSP00000416996': 'O00590',
 'ENSP00000396150': 'O00590',
 'ENSP00000272928': 'P25106',
 'ENSP00000249887': 'Q9NPB9',
 'ENSP00000504425': 'Q5JWF8',
 'ENSP00000376430': 'O96019',
 'ENSP00000397552': 'O96019',
 'ENSP00000394014': 'O96019',
 'ENSP00000160382': 'O94805',
 'ENSP00000334300': 'Q9Y615',
 'ENSP00000363799': 'Q9Y614',
 'ENSP00000253792': 'P53396',
 'ENSP00000345398': 'P53396',
 'ENSP00000377474': 'P53396',

In [52]:
# Collect prot-prot interaction data from Uniprot and add it to analysis

up_int_dict = {p:i for p, i in zip(uniprot_ids['Entry'], uniprot_ids['Interacts with']) if not isinstance(i, float)}

In [53]:
up_int_dict = {p:str(i).split('; ') for p, i in up_int_dict.items()}

In [54]:
up_int_dict_clean = {p:[str(i).split('-')[0] for i in j] for p, j in up_int_dict.items()}

In [80]:
up_spread_int = []

for keys, value in up_int_dict_clean.items():
    if isinstance(value, list):
        for prot in value:  
            up_spread_int.append((keys, prot))
    else:
        up_spread_int.append((keys, value))

In [134]:
len(up_spread_int)

176548

In [132]:
filtered_up_spread_int = [pair for pair in up_spread_int if pair[0] in protein_to_preferred_id and pair[1] in protein_to_preferred_id]

In [136]:
up_ints_1 = [i for i, p in filtered_up_spread_int]
up_ints_2 = [p for i, p in filtered_up_spread_int]

In [137]:
up_ints_1 = [re.search(r'\[(.*?)\]', p).group(1) if re.search(r'\[(.*?)\]', p) else p for p in up_ints_1]
up_ints_2 = [re.search(r'\[(.*?)\]', p).group(1) if re.search(r'\[(.*?)\]', p) else p for p in up_ints_2]

In [138]:
up_ints_1_pref = [protein_to_preferred_id[p] for p in up_ints_1]
up_ints_2_pref = [protein_to_preferred_id[p] for p in up_ints_2]

In [139]:
up_h_ints = [(one, two) for one, two in zip(up_ints_1_pref, up_ints_2_pref)]

In [140]:
# Sort each tuple and make a set to eliminate duplicate interactions

up_h_ints = {tuple(sorted(pair)) for pair in up_h_ints}
up_h_ints = list(up_h_ints)

In [141]:
len(up_h_ints)

86031

In [238]:
# Create interaction lists containing only Uniprot IDs

int_A_1 = [p.split(':')[1] for p, i in zip(intact_interactions['int_A'], intact_interactions['int_B']) if p.startswith('uniprotkb:') and i.startswith('uniprotkb:')]
int_B_1 = [i.split(':')[1] for p, i in zip(intact_interactions['int_A'], intact_interactions['int_B']) if p.startswith('uniprotkb:') and i.startswith('uniprotkb:')]

In [239]:
# Remove extra identifiers on the end of some IDs (-#) 
int_A_2 = [p.split('-')[0] for p in int_A_1]
int_B_2 = [p.split('-')[0] for p in int_B_1]

In [240]:
int_A_3 = [p for p, i in zip(int_A_2, int_B_2) if p in protein_to_preferred_id and i in protein_to_preferred_id]
int_B_3 = [i for p, i in zip(int_A_2, int_B_2) if p in protein_to_preferred_id and i in protein_to_preferred_id]

In [241]:
int_A_4 = [protein_to_preferred_id[p] for p in int_A_3]
int_B_4 = [protein_to_preferred_id[p] for p in int_B_3]

In [260]:
len(int_A_4)

891362

In [243]:
intact_h_ints = [(p, i) for p, i in zip(int_A_4, int_B_4)]

In [245]:
len(intact_h_ints)

891362

In [143]:
# Protein interaction columns in ENSP form

human_interactor1 = [p.split('.')[1] for p in list(df_human['protein1'])]
human_interactor2 = [p.split('.')[1] for p in list(df_human['protein2'])]

In [144]:
# Zip interactor columns together

zipped_human_interactors = [(one, two) for one, two in zip(human_interactor1, human_interactor2)]

In [145]:
# Remove ENSPs and their interacting partners if they are not in the ENSP-uniprot conversion table

filtered_human_interactors = [pair for pair in zipped_human_interactors if pair[0] not in ensps_cut_out and pair[1] not in ensps_cut_out]

In [146]:
zipped_h_int_uniprot = [tuple(ensp_to_pref_uniprot[p] for p in ps) for ps in filtered_human_interactors]

In [267]:
### Combine Uniprot and STRING human protein interaction data together! Unsorted at this point and may contain duplicates!

total_uniprot_ints = zipped_h_int_uniprot + up_h_ints + intact_h_ints

In [268]:
# Remove duplicate interactions from dataset

unique_h_int = {tuple(sorted(pair)) for pair in total_uniprot_ints}
unique_h_int = list(unique_h_int)

In [269]:
len(unique_h_int)

6784725

In [253]:
unique_prots_uniprot = list(set([p[0] for p in unique_h_int]) | set([p[1] for p in unique_h_int]))

In [254]:
len(unique_prots_uniprot)

22923

In [255]:
uniprot_prot_map = prot_map = {p:i for i,p in enumerate(unique_prots_uniprot)}

In [103]:
# Create adjacency matrix using Uniprot IDs

uniprot_sparse_matrix = lil_matrix((len(uniprot_prot_map), len(uniprot_prot_map)))

for prot1, prot2 in zipped_h_int_uniprot:
    uniprot_sparse_matrix[uniprot_prot_map[prot1], uniprot_prot_map[prot2]] = 1.0
    uniprot_sparse_matrix[uniprot_prot_map[prot2], uniprot_prot_map[prot1]] = 1.0

w_sparse_matrix = uniprot_sparse_matrix.tocsr()

In [104]:
# Generate set of RVFV interactors with Uniprot IDs

uniprot_rvfv_int_list = set(pd.concat([df_rvfv["node1_external_id"], df_rvfv["node2_external_id"]], axis=0, ignore_index=True))
uniprot_rvfv_int_list = {p.split('.')[1] for p in uniprot_rvfv_int_list if "9606.ENSP" in p}
uniprot_rvfv_int_list = [ensp_to_pref_uniprot[p] for p in uniprot_rvfv_int_list if p in ensp_to_pref_uniprot]

In [105]:
# Generate RVFV S array with Uniprot IDs

uniprot_rvfv_s_array = np.zeros(len(unique_prots_uniprot))

for prot in uniprot_rvfv_int_list:
    if prot in uniprot_prot_map:
        uniprot_rvfv_s_array[prot_map[prot]] = 1.0
    else:
        print(f'Protein {prot} does not interact with any human proteins.')

Protein P22061 does not interact with any human proteins.

In [137]:
{k:v for k,v in uniprot_to_name_map.items() if v.startswith('Protein-L-isoaspartate')}

{'A0A0G2JM70': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2',
 'A0A0G2JR02': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2',
 'A0A384MDK7': 'Protein-L-isoaspartate O-methyltransferase (EC 2.1.1.77)',
 'A0A3F2YNX8': 'Protein-L-isoaspartate O-methyltransferase (EC 2.1.1.77)',
 'B4E2B4': 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 1',
 'B7Z972': 'Protein-L-isoaspartate O-methyltransferase (EC 2.1.1.77)',
 'C9J0F2': 'Protein-L-isoaspartate(D-aspartate) O-methyltransferase (EC 2.1.1.77) (L-isoaspartyl protein carboxyl methyltransferase) (Protein L-isoaspartyl/D-aspartyl methyltransferase) (Protein-beta-aspartate methyltransferase)',
 'E5RGG7': 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 1',
 'F6S8N6': 'Protein-L-isoaspartate(D-aspartate) O-methyltransferase (EC 2.1.1.77) (L-isoaspartyl protein carboxyl methyltransferase) (Protein L-isoaspartyl/D-aspartyl methyltransferase) (Protein-beta-aspartate methyltransferase)',
 'F8W9F3': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2',
 'F8WAV5': 'Protein-L-isoaspartate(D-aspartate) O-methyltransferase (EC 2.1.1.77) (L-isoaspartyl protein carboxyl methyltransferase) (Protein L-isoaspartyl/D-aspartyl methyltransferase) (Protein-beta-aspartate methyltransferase)',
 'F8WAX2': 'Protein-L-isoaspartate(D-aspartate) O-methyltransferase (EC 2.1.1.77) (L-isoaspartyl protein carboxyl methyltransferase) (Protein L-isoaspartyl/D-aspartyl methyltransferase) (Protein-beta-aspartate methyltransferase)',
 'F8WDT3': 'Protein-L-isoaspartate(D-aspartate) O-methyltransferase (EC 2.1.1.77) (L-isoaspartyl protein carboxyl methyltransferase) (Protein L-isoaspartyl/D-aspartyl methyltransferase) (Protein-beta-aspartate methyltransferase)',
 'H0YBU4': 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 1',
 'H7C4X2': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase',
 'P22061': 'Protein-L-isoaspartate(D-aspartate) O-methyltransferase (PIMT) (EC 2.1.1.77) (L-isoaspartyl protein carboxyl methyltransferase) (Protein L-isoaspartyl/D-aspartyl methyltransferase) (Protein-beta-aspartate methyltransferase)',
 'Q658R8': 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 1',
 'Q96MG8': 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 1',
 'Q9NV79': 'Protein-L-isoaspartate O-methyltransferase domain-containing protein 2',
 'V9GYG6': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2',
 'V9GYL1': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2',
 'V9GYZ4': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2',
 'V9GYZ7': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2',
 'V9GZ41': 'Protein-L-isoaspartate (D-aspartate) O-methyltransferase domain containing 2'}

In [22]:
df_lasv

,#node1,node2,node1_string_internal_id,node2_string_internal_id,node1_external_id,node2_external_id,neighborhood_on_chromosome,gene_fusion,phylogenetic_cooccurrence,homology,coexpression,experimentally_determined_interaction,database_annotated,automated_textmining,combined_score
0,MYO5A,MYO5C,1858703,1845003,9606.ENSP00000382177,9606.ENSP00000261839,0,0,0,0.957,0.178,0.774,0,0.730,0.813
1,L,MYO5B,10004757,1846944,11620.L_LASSJ,9606.ENSP00000285039,0,0,0,0.000,0.000,0.000,0,0.603,0.603
2,L,MYO5C,10004757,1845003,11620.L_LASSJ,9606.ENSP00000261839,0,0,0,0.000,0.000,0.000,0,0.603,0.603
3,L,MYO5A,10004757,1858703,11620.L_LASSJ,9606.ENSP00000382177,0,0,0,0.000,0.000,0.000,0,0.603,0.603
4,DOCK7,DOCK6,1852363,1847494,9606.ENSP00000340742,9606.ENSP00000294618,0,0,0,0.978,0.000,0.596,0,0.410,0.600
5,L,DOCK6,10004757,1847494,11620.L_LASSJ,9606.ENSP00000294618,0,0,0,0.000,0.000,0.000,0,0.589,0.589
6,L,DOCK7,10004757,1852363,11620.L_LASSJ,9606.ENSP00000340742,0,0,0,0.000,0.000,0.000,0,0.589,0.589
7,L,MANBA,10004757,1843095,11620.L_LASSJ,9606.ENSP00000226578,0,0,0,0.000,0.000,0.000,0,0.579,0.579
8,L,PDE6B,10004757,1861473,11620.L_LASSJ,9606.ENSP00000420295,0,0,0,0.000,0.000,0.000,0,0.579,0.579
9,L,GUSB,10004757,1848445,11620.L_LASSJ,9606.ENSP00000302728,0,0,0,0.000,0.000,0.000,0,0.579,0.579
10,L,SFXN2,10004757,1855130,11620.L_LASSJ,9606.ENSP00000358909,0,0,0,0.000,0.000,0.000,0,0.578,0.578
11,L,SFXN4,10004757,1853234,11620.L_LASSJ,9606.ENSP00000347924,0,0,0,0.000,0.000,0.000,0,0.578,0.578
12,GUSB,MANBA,1848445,1843095,9606.ENSP00000302728,9606.ENSP00000226578,0,0,0,0.000,0.066,0.000,0,0.399,0.414

In [23]:
unique_prots = set(df_human["protein1"]) | set(df_human["protein2"])
#print(len(unique_prots))
unique_prots = list(unique_prots)
prot_map = {p:i for i,p in enumerate(unique_prots)}
prot_map

{'9606.ENSP00000380286': 0,
 '9606.ENSP00000462269': 1,
 '9606.ENSP00000499695': 2,
 '9606.ENSP00000466561': 3,
 '9606.ENSP00000478070': 4,
 '9606.ENSP00000371514': 5,
 '9606.ENSP00000329200': 6,
 '9606.ENSP00000320658': 7,
 '9606.ENSP00000483356': 8,
 '9606.ENSP00000261326': 9,
 '9606.ENSP00000317836': 10,
 '9606.ENSP00000406472': 11,
 '9606.ENSP00000493357': 12,
 '9606.ENSP00000492957': 13,
 '9606.ENSP00000225171': 14,
 '9606.ENSP00000250018': 15,
 '9606.ENSP00000360676': 16,
 '9606.ENSP00000454322': 17,
 '9606.ENSP00000436423': 18,
 '9606.ENSP00000483246': 19,
 '9606.ENSP00000238714': 20,
 '9606.ENSP00000199280': 21,
 '9606.ENSP00000369014': 22,
 '9606.ENSP00000334418': 23,
 '9606.ENSP00000360436': 24,
 '9606.ENSP00000417277': 25,
 '9606.ENSP00000251089': 26,
 '9606.ENSP00000397402': 27,
 '9606.ENSP00000228510': 28,
 '9606.ENSP00000218348': 29,
 '9606.ENSP00000263083': 30,
 '9606.ENSP00000385443': 31,
 '9606.ENSP00000490744': 32,
 '9606.ENSP00000205948': 33,
 '9606.ENSP00000320025': 34,
 '9606.ENSP00000362208': 35,
 '9606.ENSP00000383931': 36,
 '9606.ENSP00000380093': 37,
 '9606.ENSP00000333019': 38,
 '9606.ENSP00000397082': 39,
 '9606.ENSP00000342952': 40,
 '9606.ENSP00000393324': 41,
 '9606.ENSP00000377721': 42,
 '9606.ENSP00000264951': 43,
 '9606.ENSP00000431083': 44,
 '9606.ENSP00000274547': 45,
 '9606.ENSP00000245157': 46,
 '9606.ENSP00000369863': 47,
 '9606.ENSP00000326119': 48,
 '9606.ENSP00000403077': 49,
 '9606.ENSP00000479816': 50,
 '9606.ENSP00000350198': 51,
 '9606.ENSP00000225726': 52,
 '9606.ENSP00000315351': 53,
 '9606.ENSP00000217026': 54,
 '9606.ENSP00000359119': 55,
 '9606.ENSP00000324806': 56,
 '9606.ENSP00000422188': 57,
 '9606.ENSP00000245539': 58,
 '9606.ENSP00000291009': 59,
 '9606.ENSP00000363970': 60,
 '9606.ENSP00000431459': 61,
 '9606.ENSP00000418259': 62,
 '9606.ENSP00000027335': 63,
 '9606.ENSP00000215743': 64,
 '9606.ENSP00000233202': 65,
 '9606.ENSP00000308770': 66,
 '9606.ENSP00000497550': 67,
 '9606.ENSP00000308689': 68,
 '9606.ENSP00000378731': 69,
 '9606.ENSP00000368952': 70,
 '9606.ENSP00000299565': 71,
 '9606.ENSP00000359848': 72,
 '9606.ENSP00000492975': 73,
 '9606.ENSP00000407213': 74,
 '9606.ENSP00000215375': 75,
 '9606.ENSP00000354006': 76,
 '9606.ENSP00000356795': 77,
 '9606.ENSP00000252593': 78,
 '9606.ENSP00000358730': 79,
 '9606.ENSP00000347032': 80,
 '9606.ENSP00000403566': 81,
 '9606.ENSP00000274000': 82,
 '9606.ENSP00000310842': 83,
 '9606.ENSP00000364978': 84,
 '9606.ENSP00000311545': 85,
 '9606.ENSP00000361708': 86,
 '9606.ENSP00000482523': 87,
 '9606.ENSP00000294338': 88,
 '9606.ENSP00000359172': 89,
 '9606.ENSP00000338624': 90,
 '9606.ENSP00000344865': 91,
 '9606.ENSP00000481862': 92,
 '9606.ENSP00000308893': 93,
 '9606.ENSP00000257863': 94,
 '9606.ENSP00000341382': 95,
 '9606.ENSP00000326603': 96,
 '9606.ENSP00000348163': 97,
 '9606.ENSP00000253381': 98,
 '9606.ENSP00000313854': 99,
 '9606.ENSP00000483567': 100,
 '9606.ENSP00000339844': 101,
 '9606.ENSP00000291572': 102,
 '9606.ENSP00000482674': 103,
 '9606.ENSP00000350949': 104,
 '9606.ENSP00000301012': 105,
 '9606.ENSP00000300145': 106,
 '9606.ENSP00000371425': 107,
 '9606.ENSP00000356729': 108,
 '9606.ENSP00000363435': 109,
 '9606.ENSP00000370781': 110,
 '9606.ENSP00000301037': 111,
 '9606.ENSP00000301149': 112,
 '9606.ENSP00000379208': 113,
 '9606.ENSP00000403987': 114,
 '9606.ENSP00000348527': 115,
 '9606.ENSP00000247225': 116,
 '9606.ENSP00000435619': 117,
 '9606.ENSP00000299698': 118,
 '9606.ENSP00000353652': 119,
 '9606.ENSP00000382590': 120,
 '9606.ENSP00000328698': 121,
 '9606.ENSP00000301908': 122,
 '9606.ENSP00000232766': 123,
 '9606.ENSP00000266041': 124,
 '9606.ENSP00000400433': 125,
 '9606.ENSP00000369963': 126,
 '9606.ENSP00000417581': 127,
 '9606.ENSP00000301466': 128,
 '9606.ENSP00000460871': 129,
 '9606.ENSP00000377958': 130,
 '9606.ENSP00000482228': 131,
 '9606.ENSP00000499131': 132,
 '9606.ENSP00000481054': 133,
 '9606.ENSP00000264645': 134,
 '9606.ENSP00000326253': 135,
 '9606.ENSP00000345029': 136,
 '9606.ENSP00000325369': 137,
 '9606.ENSP00000362759': 138,
 '9606.ENSP00000387020': 139,
 '9606.ENSP00000314733': 140,
 '9606.ENSP00000362711': 141,
 '9606.ENSP00000269383': 142,
 '9606.ENSP00000331734': 143,
 '9606.ENSP00000385714': 144,
 '9606.ENSP00000481091': 145,
 '9606.ENSP00000304592': 146,
 '9606.ENSP00000376188': 147,
 '9606.ENSP00000274711': 148,
 '9606.ENSP00000278949': 149,
 '9606.ENSP00000320560': 150,
 '9606.ENSP00000377948': 151,
 '9606.ENSP00000428966': 152,
 '9606.ENSP00000493338': 153,
 '9606.ENSP00000396648': 154,
 '9606.ENSP00000374045': 155,
 '9606.ENSP00000343273': 156,
 '9606.ENSP00000411821': 157,
 '9606.ENSP00000379999': 158,
 '9606.ENSP00000365160': 159,
 '9606.ENSP00000370607': 160,
 '9606.ENSP00000360593': 161,
 '9606.ENSP00000381549': 162,
 '9606.ENSP00000380903': 163,
 '9606.ENSP00000466967': 164,
 '9606.ENSP00000380453': 165,
 '9606.ENSP00000366800': 166,
 '9606.ENSP00000219746': 167,
 '9606.ENSP00000320532': 168,
 '9606.ENSP00000368964': 169,
 '9606.ENSP00000380598': 170,
 '9606.ENSP00000373583': 171,
 '9606.ENSP00000253686': 172,
 '9606.ENSP00000273963': 173,
 '9606.ENSP00000305343': 174,
 '9606.ENSP00000322439': 175,
 '9606.ENSP00000290524': 176,
 '9606.ENSP00000429148': 177,
 '9606.ENSP00000251646': 178,
 '9606.ENSP00000493195': 179,
 '9606.ENSP00000378485': 180,
 '9606.ENSP00000443965': 181,
 '9606.ENSP00000423505': 182,
 '9606.ENSP00000241052': 183,
 '9606.ENSP00000491923': 184,
 '9606.ENSP00000256538': 185,
 '9606.ENSP00000489748': 186,
 '9606.ENSP00000360498': 187,
 '9606.ENSP00000386563': 188,
 '9606.ENSP00000494175': 189,
 '9606.ENSP00000304437': 190,
 '9606.ENSP00000419411': 191,
 '9606.ENSP00000256999': 192,
 '9606.ENSP00000343244': 193,
 '9606.ENSP00000362151': 194,
 '9606.ENSP00000319341': 195,
 '9606.ENSP00000494697': 196,
 '9606.ENSP00000212355': 197,
 '9606.ENSP00000235628': 198,
 '9606.ENSP00000371693': 199,
 '9606.ENSP00000320563': 200,
 '9606.ENSP00000325561': 201,
 '9606.ENSP00000254958': 202,
 '9606.ENSP00000304689': 203,
 '9606.ENSP00000366617': 204,
 '9606.ENSP00000417686': 205,
 '9606.ENSP00000289746': 206,
 '9606.ENSP00000358421': 207,
 '9606.ENSP00000355157': 208,
 '9606.ENSP00000282903': 209,
 '9606.ENSP00000406577': 210,
 '9606.ENSP00000313504': 211,
 '9606.ENSP00000501259': 212,
 '9606.ENSP00000318602': 213,
 '9606.ENSP00000369145': 214,
 '9606.ENSP00000335191': 215,
 '9606.ENSP00000373328': 216,
 '9606.ENSP00000492384': 217,
 '9606.ENSP00000358535': 218,
 '9606.ENSP00000358853': 219,
 '9606.ENSP00000384625': 220,
 '9606.ENSP00000256545': 221,
 '9606.ENSP00000438804': 222,
 '9606.ENSP00000374240': 223,
 '9606.ENSP00000234160': 224,
 '9606.ENSP00000356959': 225,
 '9606.ENSP00000242591': 226,
 '9606.ENSP00000258770': 227,
 '9606.ENSP00000287907': 228,
 '9606.ENSP00000496397': 229,
 '9606.ENSP00000379644': 230,
 '9606.ENSP00000361857': 231,
 '9606.ENSP00000499058': 232,
 '9606.ENSP00000306459': 233,
 '9606.ENSP00000367552': 234,
 '9606.ENSP00000451080': 235,
 '9606.ENSP00000386190': 236,
 '9606.ENSP00000494310': 237,
 '9606.ENSP00000164139': 238,
 '9606.ENSP00000296658': 239,
 '9606.ENSP00000245105': 240,
 '9606.ENSP00000257694': 241,
 '9606.ENSP00000339850': 242,
 '9606.ENSP00000228799': 243,
 '9606.ENSP00000312778': 244,
 '9606.ENSP00000286186': 245,
 '9606.ENSP00000464317': 246,
 '9606.ENSP00000340841': 247,
 '9606.ENSP00000315247': 248,
 '9606.ENSP00000393762': 249,
 '9606.ENSP00000384527': 250,
 '9606.ENSP00000406164': 251,
 '9606.ENSP00000434552': 252,
 '9606.ENSP00000360281': 253,
 '9606.ENSP00000351211': 254,
 '9606.ENSP00000248444': 255,
 '9606.ENSP00000354723': 256,
 '9606.ENSP00000385722': 257,
 '9606.ENSP00000253109': 258,
 '9606.ENSP00000283303': 259,
 '9606.ENSP00000274629': 260,
 '9606.ENSP00000362027': 261,
 '9606.ENSP00000399518': 262,
 '9606.ENSP00000437041': 263,
 '9606.ENSP00000361245': 264,
 '9606.ENSP00000216071': 265,
 '9606.ENSP00000428924': 266,
 '9606.ENSP00000335808': 267,
 '9606.ENSP00000397394': 268,
 '9606.ENSP00000315417': 269,
 '9606.ENSP00000379098': 270,
 '9606.ENSP00000359292': 271,
 '9606.ENSP00000398560': 272,
 '9606.ENSP00000415579': 273,
 '9606.ENSP00000359384': 274,
 '9606.ENSP00000355938': 275,
 '9606.ENSP00000374183': 276,
 '9606.ENSP00000299106': 277,
 '9606.ENSP00000376384': 278,
 '9606.ENSP00000365176': 279,
 '9606.ENSP00000353785': 280,
 '9606.ENSP00000350815': 281,
 '9606.ENSP00000386840': 282,
 '9606.ENSP00000295767': 283,
 '9606.ENSP00000423567': 284,
 '9606.ENSP00000242261': 285,
 '9606.ENSP00000449137': 286,
 '9606.ENSP00000245923': 287,
 '9606.ENSP00000390436': 288,
 '9606.ENSP00000262815': 289,
 '9606.ENSP00000286827': 290,
 '9606.ENSP00000256433': 291,
 '9606.ENSP00000262462': 292,
 '9606.ENSP00000451712': 293,
 '9606.ENSP00000383474': 294,
 '9606.ENSP00000321826': 295,
 '9606.ENSP00000362814': 296,
 '9606.ENSP00000405068': 297,
 '9606.ENSP00000205143': 298,
 '9606.ENSP00000262960': 299,
 '9606.ENSP00000297354': 300,
 '9606.ENSP00000485108': 301,
 '9606.ENSP00000331636': 302,
 '9606.ENSP00000362746': 303,
 '9606.ENSP00000375881': 304,
 '9606.ENSP00000306496': 305,
 '9606.ENSP00000383431': 306,
 '9606.ENSP00000354733': 307,
 '9606.ENSP00000240615': 308,
 '9606.ENSP00000361418': 309,
 '9606.ENSP00000261200': 310,
 '9606.ENSP00000320346': 311,
 '9606.ENSP00000397002': 312,
 '9606.ENSP00000361664': 313,
 '9606.ENSP00000264930': 314,
 '9606.ENSP00000296674': 315,
 '9606.ENSP00000494040': 316,
 '9606.ENSP00000350896': 317,
 '9606.ENSP00000296125': 318,
 '9606.ENSP00000390204': 319,
 '9606.ENSP00000413720': 320,
 '9606.ENSP00000489642': 321,
 '9606.ENSP00000356433': 322,
 '9606.ENSP00000377577': 323,
 '9606.ENSP00000378177': 324,
 '9606.ENSP00000419270': 325,
 '9606.ENSP00000439467': 326,
 '9606.ENSP00000418813': 327,
 '9606.ENSP00000343619': 328,
 '9606.ENSP00000305096': 329,
 '9606.ENSP00000368648': 330,
 '9606.ENSP00000492311': 331,
 '9606.ENSP00000295770': 332,
 '9606.ENSP00000228865': 333,
 '9606.ENSP00000265068': 334,
 '9606.ENSP00000479811': 335,
 '9606.ENSP00000357791': 336,
 '9606.ENSP00000222982': 337,
 '9606.ENSP00000350332': 338,
 '9606.ENSP00000392189': 339,
 '9606.ENSP00000270517': 340,
 '9606.ENSP00000354085': 341,
 '9606.ENSP00000472152': 342,
 '9606.ENSP00000369738': 343,
 '9606.ENSP00000320509': 344,
 '9606.ENSP00000264977': 345,
 '9606.ENSP00000355895': 346,
 '9606.ENSP00000263620': 347,
 '9606.ENSP00000357106': 348,
 '9606.ENSP00000465231': 349,
 '9606.ENSP00000444743': 350,
 '9606.ENSP00000369907': 351,
 '9606.ENSP00000370200': 352,
 '9606.ENSP00000293230': 353,
 '9606.ENSP00000490806': 354,
 '9606.ENSP00000340402': 355,
 '9606.ENSP00000368253': 356,
 '9606.ENSP00000268042': 357,
 '9606.ENSP00000367265': 358,
 '9606.ENSP00000366237': 359,
 '9606.ENSP00000436812': 360,
 '9606.ENSP00000417960': 361,
 '9606.ENSP00000300035': 362,
 '9606.ENSP00000349877': 363,
 '9606.ENSP00000307461': 364,
 '9606.ENSP00000362936': 365,
 '9606.ENSP00000479322': 366,
 '9606.ENSP00000378996': 367,
 '9606.ENSP00000481842': 368,
 '9606.ENSP00000363459': 369,
 '9606.ENSP00000377492': 370,
 '9606.ENSP00000411096': 371,
 '9606.ENSP00000421021': 372,
 '9606.ENSP00000490573': 373,
 '9606.ENSP00000225298': 374,
 '9606.ENSP00000359022': 375,
 '9606.ENSP00000361653': 376,
 '9606.ENSP00000353491': 377,
 '9606.ENSP00000252530': 378,
 '9606.ENSP00000308541': 379,
 '9606.ENSP00000371594': 380,
 '9606.ENSP00000384952': 381,
 '9606.ENSP00000312700': 382,
 '9606.ENSP00000284767': 383,
 '9606.ENSP00000365908': 384,
 '9606.ENSP00000374565': 385,
 '9606.ENSP00000429986': 386,
 '9606.ENSP00000428426': 387,
 '9606.ENSP00000290216': 388,
 '9606.ENSP00000345873': 389,
 '9606.ENSP00000495061': 390,
 '9606.ENSP00000297261': 391,
 '9606.ENSP00000406050': 392,
 '9606.ENSP00000498603': 393,
 '9606.ENSP00000368402': 394,
 '9606.ENSP00000420040': 395,
 '9606.ENSP00000394888': 396,
 '9606.ENSP00000366682': 397,
 '9606.ENSP00000365049': 398,
 '9606.ENSP00000444198': 399,
 '9606.ENSP00000037243': 400,
 '9606.ENSP00000364946': 401,
 '9606.ENSP00000379326': 402,
 '9606.ENSP00000379512': 403,
 '9606.ENSP00000482749': 404,
 '9606.ENSP00000348924': 405,
 '9606.ENSP00000178640': 406,
 '9606.ENSP00000253407': 407,
 '9606.ENSP00000331927': 408,
 '9606.ENSP00000325002': 409,
 '9606.ENSP00000278947': 410,
 '9606.ENSP00000326349': 411,
 '9606.ENSP00000407112': 412,
 '9606.ENSP00000347896': 413,
 '9606.ENSP00000316476': 414,
 '9606.ENSP00000305839': 415,
 '9606.ENSP00000456340': 416,
 '9606.ENSP00000424381': 417,
 '9606.ENSP00000361980': 418,
 '9606.ENSP00000248564': 419,
 '9606.ENSP00000398035': 420,
 '9606.ENSP00000341961': 421,
 '9606.ENSP00000475986': 422,
 '9606.ENSP00000499037': 423,
 '9606.ENSP00000300571': 424,
 '9606.ENSP00000440045': 425,
 '9606.ENSP00000469337': 426,
 '9606.ENSP00000351185': 427,
 '9606.ENSP00000480535': 428,
 '9606.ENSP00000482075': 429,
 '9606.ENSP00000282282': 430,
 '9606.ENSP00000317331': 431,
 '9606.ENSP00000331435': 432,
 '9606.ENSP00000334851': 433,
 '9606.ENSP00000337353': 434,
 '9606.ENSP00000367967': 435,
 '9606.ENSP00000312442': 436,
 '9606.ENSP00000421736': 437,
 '9606.ENSP00000350353': 438,
 '9606.ENSP00000454014': 439,
 '9606.ENSP00000398619': 440,
 '9606.ENSP00000478645': 441,
 '9606.ENSP00000360958': 442,
 '9606.ENSP00000316786': 443,
 '9606.ENSP00000420269': 444,
 '9606.ENSP00000244007': 445,
 '9606.ENSP00000295095': 446,
 '9606.ENSP00000334910': 447,
 '9606.ENSP00000262461': 448,
 '9606.ENSP00000361467': 449,
 '9606.ENSP00000385479': 450,
 '9606.ENSP00000162044': 451,
 '9606.ENSP00000289429': 452,
 '9606.ENSP00000222803': 453,
 '9606.ENSP00000370222': 454,
 '9606.ENSP00000265077': 455,
 '9606.ENSP00000370473': 456,
 '9606.ENSP00000258198': 457,
 '9606.ENSP00000242159': 458,
 '9606.ENSP00000385899': 459,
 '9606.ENSP00000422969': 460,
 '9606.ENSP00000355187': 461,
 '9606.ENSP00000356480': 462,
 '9606.ENSP00000314606': 463,
 '9606.ENSP00000364277': 464,
 '9606.ENSP00000251170': 465,
 '9606.ENSP00000349709': 466,
 '9606.ENSP00000258416': 467,
 '9606.ENSP00000494504': 468,
 '9606.ENSP00000287202': 469,
 '9606.ENSP00000399259': 470,
 '9606.ENSP00000438863': 471,
 '9606.ENSP00000498071': 472,
 '9606.ENSP00000496625': 473,
 '9606.ENSP00000293662': 474,
 '9606.ENSP00000306864': 475,
 '9606.ENSP00000379173': 476,
 '9606.ENSP00000367157': 477,
 '9606.ENSP00000455771': 478,
 '9606.ENSP00000306245': 479,
 '9606.ENSP00000398610': 480,
 '9606.ENSP00000378399': 481,
 '9606.ENSP00000485513': 482,
 '9606.ENSP00000326227': 483,
 '9606.ENSP00000470879': 484,
 '9606.ENSP00000221138': 485,
 '9606.ENSP00000491657': 486,
 '9606.ENSP00000383866': 487,
 '9606.ENSP00000381036': 488,
 '9606.ENSP00000500333': 489,
 '9606.ENSP00000368716': 490,
 '9606.ENSP00000236137': 491,
 '9606.ENSP00000450584': 492,
 '9606.ENSP00000290776': 493,
 '9606.ENSP00000420449': 494,
 '9606.ENSP00000345895': 495,
 '9606.ENSP00000442515': 496,
 '9606.ENSP00000259750': 497,
 '9606.ENSP00000386348': 498,
 '9606.ENSP00000265342': 499,
 '9606.ENSP00000364119': 500,
 '9606.ENSP00000440190': 501,
 '9606.ENSP00000275364': 502,
 '9606.ENSP00000341677': 503,
 '9606.ENSP00000366452': 504,
 '9606.ENSP00000297146': 505,
 '9606.ENSP00000453153': 506,
 '9606.ENSP00000397239': 507,
 '9606.ENSP00000473929': 508,
 '9606.ENSP00000331983': 509,
 '9606.ENSP00000250823': 510,
 '9606.ENSP00000293825': 511,
 '9606.ENSP00000301050': 512,
 '9606.ENSP00000366098': 513,
 '9606.ENSP00000220966': 514,
 '9606.ENSP00000357255': 515,
 '9606.ENSP00000484669': 516,
 '9606.ENSP00000494061': 517,
 '9606.ENSP00000309673': 518,
 '9606.ENSP00000414750': 519,
 '9606.ENSP00000352162': 520,
 '9606.ENSP00000485031': 521,
 '9606.ENSP00000364742': 522,
 '9606.ENSP00000371614': 523,
 '9606.ENSP00000436881': 524,
 '9606.ENSP00000361310': 525,
 '9606.ENSP00000259371': 526,
 '9606.ENSP00000315070': 527,
 '9606.ENSP00000388620': 528,
 '9606.ENSP00000263663': 529,
 '9606.ENSP00000362442': 530,
 '9606.ENSP00000494896': 531,
 '9606.ENSP00000292566': 532,
 '9606.ENSP00000264972': 533,
 '9606.ENSP00000469332': 534,
 '9606.ENSP00000363640': 535,
 '9606.ENSP00000364023': 536,
 '9606.ENSP00000374443': 537,
 '9606.ENSP00000448811': 538,
 '9606.ENSP00000362777': 539,
 '9606.ENSP00000488024': 540,
 '9606.ENSP00000409382': 541,
 '9606.ENSP00000164133': 542,
 '9606.ENSP00000339381': 543,
 '9606.ENSP00000234195': 544,
 '9606.ENSP00000269740': 545,
 '9606.ENSP00000433126': 546,
 '9606.ENSP00000453293': 547,
 '9606.ENSP00000275053': 548,
 '9606.ENSP00000350673': 549,
 '9606.ENSP00000347088': 550,
 '9606.ENSP00000359434': 551,
 '9606.ENSP00000433361': 552,
 '9606.ENSP00000456206': 553,
 '9606.ENSP00000252744': 554,
 '9606.ENSP00000400101': 555,
 '9606.ENSP00000270792': 556,
 '9606.ENSP00000466500': 557,
 '9606.ENSP00000296424': 558,
 '9606.ENSP00000349576': 559,
 '9606.ENSP00000379643': 560,
 '9606.ENSP00000480443': 561,
 '9606.ENSP00000433001': 562,
 '9606.ENSP00000377504': 563,
 '9606.ENSP00000263578': 564,
 '9606.ENSP00000376658': 565,
 '9606.ENSP00000280979': 566,
 '9606.ENSP00000391490': 567,
 '9606.ENSP00000331691': 568,
 '9606.ENSP00000278314': 569,
 '9606.ENSP00000436424': 570,
 '9606.ENSP00000369592': 571,
 '9606.ENSP00000335444': 572,
 '9606.ENSP00000481854': 573,
 '9606.ENSP00000216038': 574,
 '9606.ENSP00000234454': 575,
 '9606.ENSP00000252229': 576,
 '9606.ENSP00000221130': 577,
 '9606.ENSP00000264431': 578,
 '9606.ENSP00000418575': 579,
 '9606.ENSP00000324956': 580,
 '9606.ENSP00000262965': 581,
 '9606.ENSP00000369009': 582,
 '9606.ENSP00000358200': 583,
 '9606.ENSP00000222254': 584,
 '9606.ENSP00000356518': 585,
 '9606.ENSP00000383364': 586,
 '9606.ENSP00000376827': 587,
 '9606.ENSP00000445001': 588,
 '9606.ENSP00000346955': 589,
 '9606.ENSP00000468376': 590,
 '9606.ENSP00000371529': 591,
 '9606.ENSP00000368370': 592,
 '9606.ENSP00000449038': 593,
 '9606.ENSP00000333660': 594,
 '9606.ENSP00000423917': 595,
 '9606.ENSP00000493370': 596,
 '9606.ENSP00000343900': 597,
 '9606.ENSP00000412999': 598,
 '9606.ENSP00000355840': 599,
 '9606.ENSP00000408205': 600,
 '9606.ENSP00000309606': 601,
 '9606.ENSP00000465260': 602,
 '9606.ENSP00000362570': 603,
 '9606.ENSP00000362566': 604,
 '9606.ENSP00000381339': 605,
 '9606.ENSP00000402797': 606,
 '9606.ENSP00000298351': 607,
 '9606.ENSP00000199320': 608,
 '9606.ENSP00000233575': 609,
 '9606.ENSP00000443113': 610,
 '9606.ENSP00000296849': 611,
 '9606.ENSP00000312284': 612,
 '9606.ENSP00000478104': 613,
 '9606.ENSP00000480489': 614,
 '9606.ENSP00000235372': 615,
 '9606.ENSP00000386908': 616,
 '9606.ENSP00000372512': 617,
 '9606.ENSP00000386923': 618,
 '9606.ENSP00000437409': 619,
 '9606.ENSP00000464522': 620,
 '9606.ENSP00000417654': 621,
 '9606.ENSP00000441858': 622,
 '9606.ENSP00000404232': 623,
 '9606.ENSP00000455596': 624,
 '9606.ENSP00000348752': 625,
 '9606.ENSP00000366923': 626,
 '9606.ENSP00000346733': 627,
 '9606.ENSP00000245817': 628,
 '9606.ENSP00000325017': 629,
 '9606.ENSP00000343493': 630,
 '9606.ENSP00000259457': 631,
 '9606.ENSP00000378431': 632,
 '9606.ENSP00000374273': 633,
 '9606.ENSP00000383044': 634,
 '9606.ENSP00000320520': 635,
 '9606.ENSP00000290541': 636,
 '9606.ENSP00000282849': 637,
 '9606.ENSP00000340330': 638,
 '9606.ENSP00000322088': 639,
 '9606.ENSP00000371595': 640,
 '9606.ENSP00000478561': 641,
 '9606.ENSP00000429517': 642,
 '9606.ENSP00000312397': 643,
 '9606.ENSP00000309830': 644,
 '9606.ENSP00000428698': 645,
 '9606.ENSP00000321812': 646,
 '9606.ENSP00000347730': 647,
 '9606.ENSP00000266269': 648,
 '9606.ENSP00000353608': 649,
 '9606.ENSP00000372210': 650,
 '9606.ENSP00000338673': 651,
 '9606.ENSP00000491537': 652,
 '9606.ENSP00000266682': 653,
 '9606.ENSP00000364449': 654,
 '9606.ENSP00000386126': 655,
 '9606.ENSP00000320604': 656,
 '9606.ENSP00000290363': 657,
 '9606.ENSP00000420213': 658,
 '9606.ENSP00000345972': 659,
 '9606.ENSP00000482245': 660,
 '9606.ENSP00000273905': 661,
 '9606.ENSP00000470259': 662,
 '9606.ENSP00000313490': 663,
 '9606.ENSP00000307241': 664,
 '9606.ENSP00000330101': 665,
 '9606.ENSP00000296877': 666,
 '9606.ENSP00000429993': 667,
 '9606.ENSP00000315870': 668,
 '9606.ENSP00000324101': 669,

In [24]:
# Generate list of unique host proteins that interact with NSs
rvfv_prot_list = set(pd.concat([df_rvfv["node1_external_id"], df_rvfv["node2_external_id"]], axis=0, ignore_index=True))
rvfv_interactor_list = {p for p in rvfv_prot_list if "9606.ENSP" in p}

s_array = np.zeros(len(unique_prots))
for prot in rvfv_interactor_list:
    if prot in prot_map:
        s_array[prot_map[prot]] = 1.0
    else:
        print(f'Protein {prot} does not interact with any human proteins.')

Protein 9606.ENSP00000356348 does not interact with any human proteins.
Protein 9606.ENSP00000353622 does not interact with any human proteins.
Protein 9606.ENSP00000360286 does not interact with any human proteins.
Protein 9606.ENSP00000384144 does not interact with any human proteins.

In [25]:
# For Dengue type 2

denv_prot_list = set(pd.concat([df_denv["node1_external_id"], df_denv["node2_external_id"]], axis=0, ignore_index=True))
denv_interactor_list = {p for p in denv_prot_list if "9606.ENSP" in p}

denv_s_array = np.zeros(len(unique_prots))
for prot in denv_interactor_list:
    if prot in prot_map:
        denv_s_array[prot_map[prot]] = 1.0
    else:
        print(f'Protein {prot} does not interact with any human proteins.')

Protein 9606.ENSP00000334499 does not interact with any human proteins.
Protein 9606.ENSP00000412788 does not interact with any human proteins.

In [26]:
# For Lassa virus

lasv_prot_list = set(pd.concat([df_lasv["node1_external_id"], df_lasv["node2_external_id"]], axis=0, ignore_index=True))
lasv_interactor_list = {p for p in lasv_prot_list if "9606.ENSP" in p}

lasv_s_array = np.zeros(len(unique_prots))
for prot in lasv_interactor_list:
    if prot in prot_map:
        lasv_s_array[prot_map[prot]] = 1.0
    else:
        print(f'Protein {prot} does not interact with any human proteins.')

Protein 9606.ENSP00000340742 does not interact with any human proteins.
Protein 9606.ENSP00000226578 does not interact with any human proteins.

In [27]:
# For RVFV from the IntAct database

int_prots = ['9606.ENSP00000264990','9606.ENSP00000299300','9606.ENSP00000295688','9606.ENSP00000377958','9606.ENSP00000280326','9606.ENSP00000286788',
    '9606.ENSP00000220764','9606.ENSP00000265651','9606.ENSP00000216281','9606.ENSP00000360709','9606.ENSP00000247207','9606.ENSP00000302961',
    '9606.ENSP00000296464','9606.ENSP00000324173','9606.ENSP00000318687','9606.ENSP00000480150','9606.ENSP00000316032','9606.ENSP00000360154',
    '9606.ENSP00000420813','9606.ENSP00000379182','9606.ENSP00000301071','9606.ENSP00000301072','9606.ENSP00000339001','9606.ENSP00000320295',
    '9606.ENSP00000264071','9606.ENSP00000341289'
 ]

ex_rvfv_s_array = np.zeros(len(unique_prots))

for prot in int_prots:
    if prot in prot_map:
        ex_rvfv_s_array[prot_map[prot]] = 1.0
    else:
        print(f'Protein {prot} does not interact with any human proteins.')

Protein 9606.ENSP00000216281 does not interact with any human proteins.
Protein 9606.ENSP00000360709 does not interact with any human proteins.
Protein 9606.ENSP00000247207 does not interact with any human proteins.
Protein 9606.ENSP00000318687 does not interact with any human proteins.
Protein 9606.ENSP00000420813 does not interact with any human proteins.
Protein 9606.ENSP00000379182 does not interact with any human proteins.
Protein 9606.ENSP00000301071 does not interact with any human proteins.
Protein 9606.ENSP00000301072 does not interact with any human proteins.

In [28]:
lasv_s_array.sum()

8.0

In [29]:
# Pair human protein columns, map protein names to matrix coordinates, change matrix value to one at that position (and inverse position)
w_sparse_matrix = lil_matrix((len(prot_map), len(prot_map)))

for prot1, prot2 in zip(df_human['protein1'], df_human['protein2']):
    w_sparse_matrix[prot_map[prot1], prot_map[prot2]] = 1
    w_sparse_matrix[prot_map[prot2], prot_map[prot1]] = 1

w_sparse_matrix = w_sparse_matrix.tocsr()

In [115]:
# Build a function that trims the network to a certain number of rounds of connection
def select_network_subset(starting_nodes, full_network, iterations, s_array=None):
    if s_array is None:
        s_array = starting_nodes
    
    # Build out network for given number of cycles
    if iterations > 0:
        new_starting_nodes = (full_network@starting_nodes) + starting_nodes
        return select_network_subset(new_starting_nodes, full_network, iterations - 1, s_array=s_array)
    
    else:
        starting_nodes[starting_nodes > 0.0] = 1.0
        print(f"Starting nodes: {starting_nodes.sum()}")
        
        #trimmed_network_list = [p for p,m in zip(unique_prots, starting_nodes) if m > 0]
        trimmed_network_list = [p for p,m in zip(unique_prots_uniprot, starting_nodes) if m > 0]

        starting_mask = starting_nodes > 0

        trimmed_network = full_network[starting_mask,:][:,starting_mask]

        trimmed_s_array = s_array[starting_mask]
        

        return trimmed_s_array, trimmed_network, trimmed_network_list

In [116]:
# Run algorithm 

def calculate_scores(s_array, network, network_list, d_or_i='D', alpha=0.5):
    D = np.sqrt(network.sum(-1))
    D[D < 1] = 1

    normalized_matrix = network.multiply(1.0/D)
    normalized_matrix = normalized_matrix.multiply(1.0/D.T)

    I = eye(len(network_list))

    if d_or_i.lower() == 'd':
        D_tilde = normalized_matrix.sum(axis=1).A1
        #D_tilde = csr_matrix(np.matrix(np.diag(D_tilde)))
        D_tilde = diags(D_tilde, format='csr')

        L = D_tilde - normalized_matrix

    elif d_or_i.lower() == 'i':
        L = I - normalized_matrix

    else:
        print(f'{d_or_i} is an improper input for Laplacian calculation. Select D or I.')

    M = I + (alpha * L)
    y_array = spsolve(M, s_array)

    return y_array

In [117]:
# Pair scores with protein names and filter

def sort_filter_scores(y_array, network_list, viral_interactor_list, filter=True):
    prots_scores_zipped = list(zip(y_array.tolist(), network_list))
    prots_scores_sorted = sorted(prots_scores_zipped, key=lambda x: x[0], reverse=True)
    
    if filter == True:
        prots_scores_final = [tup for tup in prots_scores_sorted if tup[1] not in viral_interactor_list]
    else:
        prots_scores_final = prots_scores_sorted

    return prots_scores_final

In [22]:
# I and one-step network RVFV

s_array_one, network_one, network_list_one = select_network_subset(s_array, w_sparse_matrix.tocsr(), 1)
y_array_one = calculate_scores(s_array_one, network_one, network_list_one, d_or_i='I', alpha=0.5)

prot_scores_I_one = sort_filter_scores(y_array_one, network_list_one, rvfv_interactor_list)

Starting nodes: 7837.0

In [102]:
# D tilde and one-step network RVFV

s_array_one, network_one, network_list_one = select_network_subset(s_array, w_sparse_matrix.tocsr(), 1)
y_array_one = calculate_scores(s_array_one, network_one, network_list_one, d_or_i='D', alpha=0.5)

prot_scores_D_one = sort_filter_scores(y_array_one, network_list_one, rvfv_interactor_list, filter=False)

ValueError: dimension mismatch

In [21]:
# I and full network RVFV

s_array_one, network_one, network_list_one = select_network_subset(s_array, w_sparse_matrix.tocsr(), 3)
y_array_one = calculate_scores(s_array_one, network_one, network_list_one, d_or_i='I', alpha=0.5)

prot_scores_I_full = sort_filter_scores(y_array_one, network_list_one, rvfv_interactor_list)

Starting nodes: 19622.0

In [17]:
# D tilde and full network RVFV

s_array_one, network_one, network_list_one = select_network_subset(s_array, w_sparse_matrix.tocsr(), 3)
y_array_one = calculate_scores(s_array_one, network_one, network_list_one, d_or_i='D', alpha=0.5)

prot_scores_D_full = sort_filter_scores(y_array_one, network_list_one, rvfv_interactor_list, filter=False)

Starting nodes: 19622.0

In [18]:
# D tilde and full network with Dengue type 2

s_array_one, network_one, network_list_one = select_network_subset(denv_s_array, w_sparse_matrix.tocsr(), 3)
y_array_one = calculate_scores(s_array_one, network_one, network_list_one, d_or_i='D', alpha=0.5)

prot_scores_denv = sort_filter_scores(y_array_one, network_list_one, denv_interactor_list, filter=False)

Starting nodes: 19622.0

In [453]:
# D tilde and full network with Lassa virus

s_array_one, network_one, network_list_one = select_network_subset(lasv_s_array, w_sparse_matrix.tocsr(), 3)
y_array_one = calculate_scores(s_array_one, network_one, network_list_one, d_or_i='D', alpha=0.5)

prot_scores_lasv = sort_filter_scores(y_array_one, network_list_one, lasv_interactor_list, filter=False)

Starting nodes: 19622.0

MemoryError: Unable to allocate 2.87 GiB for an array with shape (19622, 19622) and data type float64

In [513]:
# D tilde and full network with expanded RVFV from IntAct DB

s_array_one, network_one, network_list_one = select_network_subset(ex_rvfv_s_array, w_sparse_matrix.tocsr(), 3)
y_array_one = calculate_scores(s_array_one, network_one, network_list_one, d_or_i='D', alpha=0.5)

prot_scores_ex_rvfv = sort_filter_scores(y_array_one, network_list_one, ex_rvfv_s_array, filter=False)

Starting nodes: 19622.0

In [118]:
##############################################################
## D tilde and full network with RVFV Uniprot based matrix! ##
##############################################################

up_s_array, up_network, up_network_list = select_network_subset(uniprot_rvfv_s_array, uniprot_sparse_matrix.tocsr(), 3)
up_y_array = calculate_scores(up_s_array, up_network, up_network_list, d_or_i='D', alpha=0.5)

prot_scores_up_rvfv = sort_filter_scores(up_y_array, up_network_list, up_s_array, filter=False)

Starting nodes: 18908.0

In [119]:
prot_scores_up_rvfv

[(0.7088539705414271, 'Q9UK99'),
 (0.6556791117457977, 'P78406'),
 (0.6363491026528557, 'Q01968'),
 (0.6056734478540722, 'A0A0B4J269'),
 (0.6009680269822584, 'P01574'),
 (0.587642534635575, 'Q96ST3'),
 (0.5842873814880369, 'P50991'),
 (0.4730113915710753, 'P07900'),
 (0.0019425445430861516, 'A3KFT3'),
 (0.0018227437863466633, 'Q3C1V1'),
 (0.0016894974827915104, 'P34096'),
 (0.001449726983439185, 'Q9Y5Z7'),
 (0.0014451621933871301, 'Q8TDX7'),
 (0.0012869267251021791, 'Q14162'),
 (0.001266284751332086, 'Q8NI29'),
 (0.0012176061605926112, 'Q8NFU5'),
 (0.0011634908621514315, 'Q8N5C1'),
 (0.001136218670421555, 'Q9UKT5'),
 (0.0011175092059309158, 'O75446'),
 (0.001078889502351369, 'O94806'),
 (0.0010684940225789642, 'Q9Y3V2'),
 (0.001058581622397925, 'Q5PSV4'),
 (0.001048069697684027, 'P0C2W1'),
 (0.0010464830012996847, 'Q5XX13'),
 (0.00103938979034046, 'O15226'),
 (0.0010387093106689223, 'Q96EF6'),
 (0.0010338503206705507, 'B4DQE3'),
 (0.0010255702960208027, 'B7Z5P0'),
 (0.0010116426035091408, 'Q9UHR6'),
 (0.001006769367561613, 'O75426'),
 (0.0010021930491773928, 'Q12852'),
 (0.0009972158940795722, 'Q7Z6K3'),
 (0.0009941690847499634, 'P29590'),
 (0.0009893125060167953, 'A0AAR1ZLH9'),
 (0.0009844166669959699, 'Q9H1M0'),
 (0.0009796541180743272, 'P78560'),
 (0.0009585024448322461, 'Q96ME1'),
 (0.00095159615484938, 'Q9BZL6'),
 (0.0009463428534180709, 'Q9HAT8'),
 (0.0009437155061325258, 'G5E9I4'),
 (0.0009414940577240561, 'Q99627'),
 (0.000922109951346853, 'A0A1B0GVZ6'),
 (0.0009142769645370174, 'Q96KP6'),
 (0.0009071025507385431, 'Q9NRD1'),
 (0.0009057231225713385, 'Q15018'),
 (0.0009056823815763453, 'Q5VV17'),
 (0.0009024836782737837, 'O95639'),
 (0.000901868855730447, 'Q13888'),
 (0.0009015572998745175, 'B4DLM2'),
 (0.0008979270347821002, 'P36952'),
 (0.0008979018441958195, 'K4DI93'),
 (0.0008971064394021539, 'Q9H5V7'),
 (0.0008968306320906035, 'O15033'),
 (0.0008932485591906071, 'Q14149'),
 (0.0008929559733076525, 'Q96RS6'),
 (0.0008929290505960641, 'Q8TCG2'),
 (0.000890419054485489, 'Q86VG3'),
 (0.0008892197101186088, 'Q7Z6Z7'),
 (0.0008881851357776399, 'B7Z9H7'),
 (0.000881896790508642, 'Q9NZD2'),
 (0.0008809614803029431, 'Q9HAJ7'),
 (0.0008800275533909022, 'Q86VP6'),
 (0.0008778890191077994, 'E7EWH8'),
 (0.0008773412663030533, 'Q9NUJ3'),
 (0.0008748048406693108, 'Q9UKC9'),
 (0.0008609733774287272, 'Q14258'),
 (0.000856441259785772, 'Q9UKA1'),
 (0.0008563495650035673, 'Q9BQS6'),
 (0.0008561952986086888, 'O43283'),
 (0.0008523388447152039, 'B4DYA3'),
 (0.0008522942785594279, 'G3V4B8'),
 (0.0008510102512301532, 'Q3KRA6'),
 (0.0008499536068199276, 'Q9HCN4'),
 (0.0008477639143049475, 'Q8N1E6'),
 (0.0008465638441961735, 'Q92613'),
 (0.0008463583853559386, 'Q9NX47'),
 (0.0008460365961759471, 'P46019'),
 (0.0008458881974730889, 'Q6ICB4'),
 (0.0008457449231519079, 'P52294'),
 (0.0008452537738914417, 'Q9HB20'),
 (0.0008437768542415501, 'Q9H8X2'),
 (0.0008433176353239489, 'Q9Y237'),
 (0.0008419632102807221, 'Q99470'),
 (0.0008411962378794524, 'Q96JA3'),
 (0.0008409395300473262, 'Q86VQ1'),
 (0.0008389869416566058, 'O94952'),
 (0.0008389850341313953, 'Q8IUD6'),
 (0.0008381408171742673, 'Q9Y6I7'),
 (0.000836547082291941, 'Q9HB14'),
 (0.0008358691550993082, 'Q7Z3K6'),
 (0.000835666740847938, 'P51610'),
 (0.0008341488511811991, 'Q6P4I2'),
 (0.0008341178386150688, 'Q96MN2'),
 (0.0008337836109858005, 'Q9H7U1'),
 (0.0008261657303863435, 'Q03393'),
 (0.0008202225586753469, 'Q9NUG6'),
 (0.0008169453829503802, 'Q92783'),
 (0.0008163623530175043, 'Q8IWJ2'),
 (0.0008147536138072877, 'Q96G25'),
 (0.0008115410294966298, 'P32780'),
 (0.0008107175137942224, 'Q6ZRK6'),
 (0.0008092061795673452, 'A0A087WT04'),
 (0.0008085210513043948, 'Q8ND25'),
 (0.0008078612751175696, 'Q6P1K2'),
 (0.0008049999177148822, 'Q9BPW8'),
 (0.0008038381993354337, 'P61758'),
 (0.0008023172409399584, 'Q9BZD6'),
 (0.0008016034458219684, 'Q7Z3B0'),
 (0.0008005251568304878, 'M0QXC7'),
 (0.0007980094397331201, 'Q9NRN7'),
 (0.0007965685647439619, 'P41236'),
 (0.0007960642824777845, 'Q96QC4'),
 (0.0007958781920511931, 'B4DX44'),
 (0.0007944012129834024, 'P51178'),
 (0.0007942547195451305, 'Q9NV79'),
 (0.0007932774507022505, 'B1ATL7'),
 (0.0007931939193202331, 'B7Z1P2'),
 (0.0007920601086186218, 'Q9BSF8'),
 (0.0007918125952059971, 'Q9BZM4'),
 (0.0007904025693329328, 'Q9UK73'),
 (0.0007891591377850495, 'O43399'),
 (0.0007886107392576112, 'Q8N6K7'),
 (0.0007872289268684884, 'Q8TAF3'),
 (0.0007867400894389481, 'Q9H9H4'),
 (0.0007838137286342245, 'P61201'),
 (0.0007835872000185657, 'P35557'),
 (0.000781930302361087, 'P54296'),
 (0.0007807313638060223, 'Q5VTB9'),
 (0.0007748244354310609, 'Q9BZI7'),
 (0.0007745739762089777, 'P36406'),
 (0.0007744307492102396, 'Q9UKT7'),
 (0.0007742747187777563, 'O43255'),
 (0.0007660346841491814, 'Q7Z7B0'),
 (0.0007656007012566349, 'O00463'),
 (0.0007645207246981347, 'Q9NPH2'),
 (0.0007614368987677685, 'Q9BZM6'),
 (0.0007608556414350022, 'P23246'),
 (0.0007597645413680946, 'Q8NFH4'),
 (0.0007592075589344293, 'Q969U6'),
 (0.0007590722087451156, 'Q9Y3S2'),
 (0.0007541277990699441, 'Q8ND56'),
 (0.000753844810045605, 'Q9HCE5'),
 (0.0007511282767911568, 'O00170'),
 (0.0007490894576765925, 'Q9UHH9'),
 (0.0007473292559817724, 'Q6P6C2'),
 (0.00074233769282949, 'O14717'),
 (0.0007393069396278887, 'P61970'),
 (0.0007390452405080018, 'P37198'),
 (0.00073858904654278, 'Q9H171'),
 (0.000735473032932694, 'Q15287'),
 (0.0007323461499362056, 'Q4ZJI4'),
 (0.0007317736367508439, 'Q6FIF0'),
 (0.000731354656214326, 'Q96EP1'),
 (0.0007313379892734411, 'Q13619'),
 (0.0007311573129928447, 'B7Z4P9'),
 (0.0007298329005808052, 'Q9HBJ8'),
 (0.0007296250110451133, 'P52732'),
 (0.0007294511553197865, 'Q86YB8'),
 (0.0007290267725378232, 'Q9BZY9'),
 (0.0007286710654922928, 'Q9P2B4'),
 (0.0007286403969668429, 'Q9UNE7'),
 (0.0007283727816900588, 'P19525'),
 (0.0007278799435515516, 'A6NMQ1'),
 (0.0007263559480045768, 'O95628'),
 (0.0007260968312388372, 'Q5JW98'),
 (0.0007253660346485503, 'Q6ZW13'),
 (0.000723798950692072, 'Q8TF61'),
 (0.0007234500077670881, 'Q92551'),
 (0.0007230749515443762, 'Q9BXU2'),
 (0.0007229360151272068, 'Q9UN86'),
 (0.0007225911100710779, 'Q96QD5'),
 (0.0007225063162345501, 'Q9BZJ0'),
 (0.0007218014949050389, 'Q9UEG4'),
 (0.0007217945987158354, 'P51816'),
 (0.0007215220687966415, 'Q9BZM5'),
 (0.0007212259229038018, 'Q93009'),
 (0.0007197120580019647, 'O60573'),
 (0.0007194734321194847, 'P61962'),
 (0.0007189911518991127, 'O75807'),
 (0.0007179564646912174, 'O60518'),
 (0.000717711733985579, 'Q9NWL6'),
 (0.0007166862961734655, 'A0A087WTF0'),
 (0.000716613827509247, 'Q9NUP1'),
 (0.0007162536530980298, 'J3KNY7'),
 (0.0007161123963882585, 'O00629'),
 (0.0007158350221446085, 'Q969P6'),
 (0.0007146589937760236, 'Q9H2X6'),
 (0.0007145784785264135, 'Q9Y6M4'),
 (0.0007134647976603295, 'Q8NEE6'),
 (0.0007133391281117449, 'Q9Y577'),
 (0.0007128525438049775, 'Q8WV41'),
 (0.0007120822609490508, 'Q8N961'),
 (0.0007120819561316206, 'Q6H3X3'),
 (0.0007118892097522586, 'O95361'),
 (0.000711830371225944, 'Q15276'),
 (0.0007111551638110099, 'Q96EP0'),
 (0.0007107498625117865, 'O14681'),
 (0.0007097449361436585, 'D6RAK4'),
 (0.0007096541339878616, 'Q8IWW6'),
 (0.0007072152270982038, 'Q9P000'),
 (0.0007071364593639983, 'Q6ZVL6'),
 (0.0007070361234941268, 'O14578'),
 (0.0007060016186555547, 'Q9NPC7'),
 (0.0007054696302761053, 'Q16514'),
 (0.0007041526030668239, 'A6NDZ8'),
 (0.0007039886124136882, 'Q14653'),
 (0.0007027257047048264, 'Q96J02'),
 (0.0007023663466441229, 'H0Y614'),
 (0.0007020954507446749, 'Q9HB71'),
 (0.0007017520415703927, 'P60673'),
 (0.0007016900045098542, 'O00165'),
 (0.0007011520463192763, 'B4DRN3'),
 (0.0007005012547308909, 'Q9UKT8'),
 (0.0007004585976588634, 'O60583'),
 (0.0006998515444443943, 'Q96FV9'),
 (0.000698185480438999, 'P29401'),
 (0.0006973662759122626, 'Q8NGF6'),
 (0.0006964498950837969, 'A2I2P0'),
 (0.0006963291620696563, 'A9QM74'),
 (0.000695858560631153, 'Q8NEZ5'),
 (0.0006958141154353266, 'P63165'),
 (0.000693972201981614, 'Q9NP79'),
 (0.0006926381578120504, 'Q96CF2'),
 (0.0006914229415750708, 'Q7Z309'),
 (0.0006906301427923609, 'O15516'),
 (0.0006894660118893189, 'Q9Y4Y9'),
 (0.0006894206753380877, 'Q9UH92'),
 (0.0006878694857292118, 'Q86TU7'),
 (0.0006871483834523878, 'Q8TDG2'),
 (0.000685501496524881, 'P62253'),
 (0.0006849359128578088, 'Q674R7'),
 (0.0006839607319481664, 'Q02386'),
 (0.0006839200081461053, 'Q9H9E1'),
 (0.000683417843280441, 'Q9NRJ4'),
 (0.0006833974978701931, 'Q96D70'),
 (0.0006833261603825741, 'Q5W0Z9'),
 (0.0006827386473831135, 'P31150'),
 (0.000682276880866811, 'Q96GD4'),
 (0.0006814354581265393, 'Q6ZP29'),
 (0.0006810973115157361, 'Q13616'),
 (0.000680554008906994, 'Q6PK04'),
 (0.000680131819229994, 'P55345'),
 (0.0006800637534349233, 'Q9NXK8'),
 (0.0006798659861231407, 'Q13118'),
 (0.0006786194992830952, 'Q9Y2S7'),
 (0.0006773391772145166, 'O95424'),
 (0.0006771514733463713, 'O60307'),
 (0.0006749236957753411, 'O94812'),
 (0.0006738335029386613, 'Q6P4D5'),
 (0.0006727447535242115, 'P78318'),
 (0.0006727247879277915, 'Q8IYH5'),
 (0.000672715690820388, 'Q86W26'),
 (0.0006722455699983307, 'P60510'),
 (0.0006712515136123225, 'O14530'),
 (0.0006711620340233142, 'Q9NXF7'),
 (0.0006711475047643806, 'A2A2L5'),
 (0.0006709827893735499, 'Q7RTT9'),
 (0.0006705094755241216, 'Q8NEF9'),
 (0.0006705028136630264, 'Q9NX02'),
 (0.0006702821277263778, 'A0A0U1RQI7'),
 (0.0006694790569907385, 'Q8NEG7'),
 (0.0006693100683617688, 'Q13409'),
 (0.0006685625256554624, 'Q16576'),
 (0.0006683437070914408, 'K7ER24'),
 (0.0006672601151485834, 'O75688'),
 (0.0006668672084328013, 'Q05086'),
 (0.0006654760678163686, 'Q9NUQ7'),
 (0.0006652938180354412, 'Q9UI26'),
 (0.0006649886033522177, 'Q9Y3I1'),
 (0.000664875159625753, 'P20340'),
 (0.0006643868543730844, 'P46736'),
 (0.0006642177578069104, 'Q14134'),
 (0.0006641171806306669, 'B7ZVW6'),
 (0.0006634600329251038, 'Q9UBJ2'),
 (0.0006629260850504362, 'O43822'),
 (0.0006628963167323275, 'Q07890'),
 (0.0006628846912513916, 'Q08380'),
 (0.0006623612905034633, 'Q8WVM0'),
 (0.0006617256982203192, 'P46020'),
 (0.0006610180405507463, 'A0A1B0GUY1'),
 (0.0006609035708591284, 'Q3T906'),
 (0.0006600311563305975, 'Q13526'),
 (0.0006597767507690272, 'P36873'),
 (0.0006590699884038155, 'P23497'),
 (0.000658170667832463, 'Q8NHR9'),
 (0.000657726429424223, 'O60684'),
 (0.0006568787905829794, 'Q8IW45'),
 (0.0006566635544521738, 'P50750'),
 (0.0006566622400776621, 'Q14980'),
 (0.0006559492005670966, 'Q9UK97'),
 (0.0006556464905294971, 'A0A087WYF9'),
 (0.0006555258942950427, 'Q9H6E4'),
 (0.0006553639437379891, 'O15347'),
 (0.0006553445079391134, 'E7ERS3'),
 (0.0006526102028658, 'O14867'),
 (0.000652266394044052, 'Q9NQ89'),
 (0.0006512039270628691, 'Q14964'),
 (0.0006510559646014431, 'M0QXB4'),
 (0.0006508407937427347, 'P06454'),
 (0.0006508279960395135, 'Q08334'),
 (0.0006507007120775441, 'Q7L3B6'),
 (0.0006506622409737158, 'O95600'),
 (0.000650315429626858, 'Q5TA12'),
 (0.000650000387919581, 'Q9NRJ5'),
 (0.0006496107709742164, 'Q9NVF7'),
 (0.0006492871538986215, 'P15313'),
 (0.0006487578667669476, 'H3BM93'),
 (0.000648479922748663, 'P49773'),
 (0.0006483808825474072, 'Q9ULK4'),
 (0.0006483152803586329, 'Q6IQ49'),
 (0.0006468589530952555, 'Q6NYC1'),
 (0.0006461459964332417, 'P30626'),
 (0.0006459918005311781, 'Q9Y4K3'),
 (0.0006455420382377333, 'Q9BUZ4'),
 (0.0006453336050677164, 'Q9P0N8'),
 (0.0006453109434789844, 'Q86Y13'),
 (0.0006451620554564086, 'Q5VY80'),
 (0.0006447821429077151, 'Q5MNV8'),
 (0.0006432327998065391, 'P08603'),
 (0.0006429916257191976, 'Q8N4B1'),
 (0.0006417237090584407, 'P63215'),
 (0.0006414524911764949, 'P52292'),
 (0.000640240091346894, 'Q6X9E4'),
 (0.0006392346499008443, 'Q15311'),
 (0.0006391770422216529, 'P57729'),
 (0.0006390559100307666, 'P82279'),
 (0.0006387795859451394, 'Q96KP1'),
 (0.0006385006618387302, 'Q08211'),
 (0.0006373870852460538, 'O95630'),
 (0.0006372496481698505, 'Q86WI0'),
 (0.0006367628874001389, 'P61088'),
 (0.0006364933973734947, 'B3KNP2'),
 (0.0006360147219070107, 'Q6ZNL6'),
 (0.0006357913580526891, 'Q6IQ26'),
 (0.0006353644299497724, 'Q15776'),
 (0.0006350935502200299, 'O95479'),
 (0.0006343385060569187, 'Q86XK2'),
 (0.0006339028285673556, 'Q8TE76'),
 (0.000633893621587131, 'P51116'),
 (0.0006329530949148093, 'Q9UNA4'),
 (0.0006326110159943674, 'Q15843'),
 (0.0006317827099549646, 'P51003'),
 (0.0006308338076041398, 'A6NGB7'),
 (0.0006308077147996136, 'Q13077'),
 (0.0006297034801432462, 'Q9NUD7'),
 (0.0006294971275402382, 'O15379'),
 (0.0006294874212421874, 'P35659'),
 (0.0006291967199966971, 'O14830'),
 (0.0006290122717426496, 'Q969Y2'),
 (0.0006285262251400999, 'Q16630'),
 (0.0006284768382181036, 'Q9H1J1'),
 (0.0006284231765330932, 'Q9H0F6'),
 (0.0006281073672570016, 'Q8WWZ7'),
 (0.0006279844372623783, 'O00743'),
 (0.0006278245383574571, 'Q9BVV2'),
 (0.0006275630815996104, 'B2RUY7'),
 (0.0006272087029085258, 'P18583'),
 (0.0006271235948678791, 'Q96I25'),
 (0.0006270316444815361, 'Q86US8'),
 (0.0006262246751968359, 'Q8WX94'),
 (0.0006261460468440623, 'O75832'),
 (0.0006250431001199738, 'Q6ZQY2'),
 (0.0006246818155215608, 'Q8N3Y1'),
 (0.0006242168332452454, 'C9JBF1'),
 (0.0006236015331252147, 'F8VSB2'),
 (0.0006235990256479153, 'Q8NCE2'),
 (0.0006232956867542077, 'P49642'),
 (0.0006229042261396016, 'B1AH48'),
 (0.0006228015533976762, 'Q969T3'),
 (0.0006226802039554172, 'Q9BXU3'),
 (0.0006222607334549035, 'P35573'),
 (0.000622094570595843, 'Q9H8T0'),
 (0.0006216970183437098, 'Q8TBC4'),
 (0.0006202968273873545, 'Q9Y230'),
 (0.0006200406312235697, 'Q9H307'),
 (0.0006188797157974013, 'Q8N3I7'),
 (0.0006183208077033327, 'Q8N6S4'),
 (0.000618139013106204, 'H0YM59'),
 (0.0006178458370914679, 'O95071'),
 (0.0006170482128500538, 'O00422'),
 (0.0006168602655791994, 'Q96SF2'),
 (0.0006165401104135312, 'Q9H2P9'),
 (0.0006163698390600196, 'O00327'),
 (0.0006160304186036826, 'Q96LW4'),
 (0.0006160045317892502, 'O60524'),
 (0.0006158552287870849, 'Q9BXJ7'),
 (0.0006157068023397171, 'Q15369'),
 (0.000615263696133635, 'Q9GZN1'),
 (0.0006152199884419884, 'Q969H0'),
 (0.0006150585688412554, 'O75592'),
 (0.0006144276759446691, 'Q8NI27'),
 (0.0006141286883542492, 'Q9Y2E6'),
 (0.0006141244480727914, 'Q13618'),
 (0.0006126222803671705, 'Q15233'),
 (0.0006123775843215287, 'Q6UXN9'),
 (0.0006120792664283364, 'Q9H0M0'),
 (0.0006119576744624033, 'P46934'),
 (0.0006113735362709755, 'Q9UMS4'),
 (0.0006109729497516802, 'Q96AP4'),
 (0.0006101748169007663, 'Q9ULU4'),
 (0.000610112260532628, 'Q8N1V2'),
 (0.0006099783681395444, 'Q9UBU9'),
 (0.0006099069204868213, 'P50395'),
 (0.0006094848772410856, 'Q99471'),
 (0.0006093472960981037, 'Q93034'),
 (0.0006092649151551768, 'Q96PM5'),
 (0.0006087495590239165, 'P55010'),
 (0.000608506834886123, 'Q9UHX1'),
 (0.0006081261242088616, 'O00505'),
 (0.0006080585559603256, 'Q7Z333'),
 (0.0006074982072716043, 'Q9BZ72'),
 (0.0006073724221192561, 'A0A0D2X7Z3'),
 (0.0006072368534855439, 'Q8NHM5'),
 (0.0006070026524569295, 'Q96J01'),
 (0.0006068629375582521, 'P11387'),
 (0.0006065805798331332, 'P60520'),
 (0.0006064550734007939, 'Q9UHG3'),
 (0.0006056368407944858, 'Q7Z7K6'),
 (0.0006056180306009339, 'Q8WYQ5'),
 (0.0006054654437936521, 'Q6SJ96'),
 (0.0006054613113630758, 'Q15434'),
 (0.0006047821694362931, 'Q9Y450'),
 (0.0006043746977828688, 'P21580'),
 (0.0006034755362455163, 'Q9NZZ3'),
 (0.0006033890851159982, 'Q9Y6Q9'),
 (0.0006033484689603364, 'Q14542'),
 (0.0006031978691714391, 'Q92621'),
 (0.0006031390709239661, 'Q9Y297'),
 (0.0006028373514701086, 'O15164'),
 (0.0006022459772441338, 'Q9H5Q4'),
 (0.0006019436115310019, 'Q96L92'),
 (0.0006016981368995629, 'P0DMW2'),
 (0.0006012211332427026, 'Q96DB2'),
 (0.0006006033877335535, 'P26583'),
 (0.0005995848978583196, 'Q5JUX0'),
 (0.0005995101962337683, 'P28288'),
 (0.0005991485505530887, 'B9EJG8'),
 (0.0005991045879372523, 'P51114'),
 (0.0005987484523683666, 'Q9UNQ2'),
 (0.0005985379295392652, 'Q5SRE5'),
 (0.0005980464535971875, 'Q9Y6G9'),
 (0.0005977132825179535, 'Q9Y2H2'),
 (0.000597486583266308, 'Q9BZD2'),
 (0.0005974051278638629, 'Q99816'),
 (0.0005963692702014539, 'F8WC89'),
 (0.0005961218418796062, 'Q9H832'),
 (0.0005958619878081965, 'Q8N8R7'),
 (0.0005958552302700547, 'Q9H3H3'),
 (0.000595637886589412, 'P52594'),
 (0.0005950408134216395, 'P61011'),
 (0.0005942381185691171, 'O14668'),
 (0.0005931736310417777, 'Q9NZJ0'),
 (0.0005926453993515848, 'Q5JX71'),
 (0.0005924671461389039, 'Q8TDY2'),
 (0.0005922928452713672, 'Q9GZS0'),
 (0.000592090885076448, 'P84085'),
 (0.0005917910694721634, 'Q9Y3A3'),
 (0.0005913531024070789, 'Q9HCE7'),
 (0.0005911274110531111, 'Q13572'),
 (0.0005910840932091665, 'O94826'),
 (0.0005910801061030997, 'P48444'),
 (0.0005909757043060686, 'Q8N4L2'),
 (0.0005909002574775649, 'F5H423'),
 (0.000590580761757648, 'Q13595'),
 (0.0005901865544403174, 'O43918'),
 (0.0005901784261356736, 'P05455'),
 (0.0005900694340690138, 'P62495'),
 (0.0005900132028809755, 'Q9BRG2'),
 (0.0005898635819671737, 'Q8NFJ9'),
 (0.0005896053392537335, 'Q9BV73'),
 (0.0005895183417762046, 'Q86UY6'),
 (0.000589360063334222, 'Q96EY8'),
 (0.0005893456847956457, 'M0QX15'),
 (0.0005892201712902347, 'Q9UL18'),
 (0.00058882693698949, 'A6NKT7'),
 (0.0005888139630867589, 'A0A1W2PS79'),
 (0.0005883253245493458, 'Q9NPJ1'),
 (0.0005874650297436478, 'Q9Y2B9'),
 (0.000586831427984673, 'Q5VU92'),
 (0.0005866897661822264, 'P22304'),
 (0.0005852023379735049, 'Q05CY8'),
 (0.0005842376567577337, 'Q8N302'),
 (0.0005839992215469294, 'Q8N3F8'),
 (0.0005838490055235729, 'P28328'),
 (0.0005834223547986193, 'P55795'),
 (0.0005828525700725736, 'Q9UJV9'),
 (0.0005826340480551365, 'Q02447'),
 (0.0005825229682741515, 'Q9NRD0'),
 (0.0005824976457796801, 'Q0VAA2'),
 (0.0005821449369054617, 'Q15717'),
 (0.0005818786608930735, 'Q9NZN4'),
 (0.0005813002750947969, 'Q9H0T7'),
 (0.0005811087008544618, 'A7MCY6'),
 (0.000580311810230399, 'Q15075'),
 (0.0005802813024222141, 'O94941'),
 (0.0005792627068296957, 'H7C4C9'),
 (0.0005792611861227509, 'P25791'),
 (0.0005778019262595148, 'Q9BV36'),
 (0.0005775535276634657, 'A0T3B2'),
 (0.0005773552386779568, 'Q16531'),
 (0.0005772468090031442, 'O60942'),
 (0.0005771585645799164, 'Q8WW12'),
 (0.0005753632965004869, 'P32456'),
 (0.0005750476187051357, 'P51784'),
 (0.0005742197957514818, 'Q6DKJ4'),
 (0.0005741228924709806, 'Q6P3W2'),
 (0.0005735561710769903, 'Q96CX3'),
 (0.0005732008660237209, 'Q8WVY7'),
 (0.0005730610919908206, 'Q9Y3Y2'),
 (0.000572849279390277, 'Q8IUQ4'),
 (0.0005725836527805652, 'Q12996'),
 (0.0005724530043081607, 'P59046'),
 (0.0005723662677589613, 'Q07666'),
 (0.0005721420885945163, 'P21399'),
 (0.0005720947868465915, 'Q13114'),
 (0.0005720900996253092, 'Q96N67'),
 (0.0005720380333033659, 'Q5HYC2'),
 (0.0005720027791713876, 'Q8NBS9'),
 (0.0005719670463616379, 'Q9ULR3'),
 (0.0005712337870640579, 'A1L447'),
 (0.0005711817985890494, 'P25325'),
 (0.0005709759059840327, 'O43175'),
 (0.0005706774581195318, 'P04062'),
 (0.0005704756663432315, 'Q7Z434'),
 (0.0005702911762488516, 'P36405'),
 (0.0005702505151267157, 'A9UHW6'),
 (0.0005702242696160075, 'P12956'),
 (0.0005699151072795366, 'P0C5J1'),
 (0.0005694495680956681, 'Q96NL6'),
 (0.0005683152375483139, 'Q5U3C3'),
 (0.0005675980610009408, 'Q7L8L6'),
 (0.0005671305116689404, 'P16298'),
 (0.0005669260034629719, 'Q6P1J9'),
 (0.0005663303263614139, 'Q13309'),
 (0.0005661753428344847, 'Q9UKW6'),
 (0.0005654959533036093, 'A6PVI3'),
 (0.0005653913612308443, 'Q6PJI9'),
 (0.0005653886304229391, 'Q8TB24'),
 (0.0005650501334831497, 'Q99666'),
 (0.000564372018116198, 'Q96K76'),
 (0.0005641589843179908, 'O95758'),
 (0.0005641274055583365, 'Q15257'),
 (0.000563793909458551, 'Q8ND82'),
 (0.0005636050896677476, 'Q0VAF6'),
 (0.0005633885220287104, 'Q96AZ1'),
 (0.0005633694855128218, 'P59044'),
 (0.000563284773669194, 'O95147'),
 (0.0005628708495781081, 'E9PKC0'),
 (0.0005627006770128884, 'E7EX90'),
 (0.0005623085499211884, 'Q9NRM0'),
 (0.0005622652737953416, 'O75844'),
 (0.0005622516407410273, 'Q9ULC4'),
 (0.0005619956145317432, 'P49411'),
 (0.0005618890258200033, 'Q96E52'),
 (0.000561870569783641, 'Q9Y6K8'),
 (0.0005617929908173496, 'P18577'),
 (0.0005615506971540549, 'Q96DI7'),

In [111]:
up_scores_df = pd.DataFrame(index=[p for _,p in prot_scores_up_rvfv], columns=["RVFV"])

up_scores = [
    (prot_scores_up_rvfv, 'RVFV'),
]

for prot_scores, column_name in up_scores:
    for s, p in prot_scores:
        up_scores_df.loc[p, column_name] = s

TypeError: unhashable type: 'csr_matrix'

In [515]:
# Add scores to dataframe

scores_df = pd.DataFrame(index=[p.split('.')[1] for _,p in prot_scores_D_full], columns=["RVFV"])

scores = [
    (prot_scores_D_full, 'RVFV'),
    (prot_scores_denv, 'DENV'),
    (prot_scores_lasv, 'LASV'),
    (prot_scores_ex_rvfv, 'RVFVex')
]

for prot_scores, column_name in scores:
    for s, p in prot_scores:
        scores_df.loc[p.split('.')[1], column_name] = s

In [516]:
scores_df

                     RVFV          DENV          LASV    RVFVex
ENSP00000265651  0.714409  2.489288e-04  3.965504e-05  0.714192
ENSP00000360154  0.659057  4.618905e-05  3.075052e-04  0.659134
ENSP00000451560  0.648018  4.566916e-04  3.546594e-04  0.000815
ENSP00000369581  0.647397  6.473888e-01  3.045371e-04  0.000545
ENSP00000377958  0.642018  5.445292e-04  5.433123e-05  0.642814
...                   ...           ...           ...       ...
ENSP00000485141  0.000001  9.474587e-07  5.989195e-07  0.000002
ENSP00000497579  0.000001  7.816776e-07  7.377077e-07  0.000002
ENSP00000499042  0.000001  8.156735e-07  1.143150e-06  0.000002
ENSP00000497547  0.000001  8.322699e-07  7.347714e-07  0.000002
ENSP00000490135  0.000001  3.454664e-06  4.415158e-07  0.000004

[19622 rows x 4 columns]

In [24]:
df_id_conversions

,Uniprot_ID,uk1,uk2,uk3,uk4,uk5,GO_IDs,uk6,uk7,uk8,...,uk11,uk12,uk13,uk14,uk15,uk16,ENSG,ENST,ENSP,uk17
0,P62258,1433E_HUMAN,7531,NP_006752.1,374074368; 62131678; 67464424; 194379794; 2210...,2BR9:A; 3UAL:A; 3UBW:A; 6EIH:A; 7C8E:A; 7C8E:B...,GO:0005737; GO:0005829; GO:0005783; GO:0070062...,UniRef100_P62258,UniRef90_P62258,UniRef50_P62258,...,9606,605066,NaN,7644510; 8858348; 8684458; 20417184; 14702039;...,U20972; U54778; U43399; U43430; U28936; AB0171...,AAC50175.1; AAC50710.1; AAC50625.1; AAD00026.1...,ENSG00000108953.17; ENSG00000274474.3,ENST00000264335.13; ENST00000571732.5; ENST000...,ENSP00000264335.8; ENSP00000461762.1; ENSP0000...,15838597; 11782387; 12657644; 14966136; 153649...
1,Q04917,1433F_HUMAN,7533,NP_003396.1,4507951; 460779; 437363; 83754686; 12804373; 8...,2C63:A; 2C63:B; 2C63:C; 2C63:D; 2C74:A; 2C74:B...,GO:0150048; GO:0005737; GO:0005829; GO:0070062...,UniRef100_Q04917,UniRef90_Q04917,UniRef50_Q04917,...,9606,113508,NaN,8218406; 1578511; 8561965; 8812417; 15461802; ...,L20422; X80536; X78138; X57345; D78577; S80794...,AAA35483.1; CAA56676.1; CAA55017.1; CAA40620.1...,ENSG00000128245.15,ENST00000248975.6,ENSP00000248975.5,10206237; 11121172; 11996670; 12176995; 124801...
2,P61981,1433G_HUMAN,7532,NP_036611.2,6016838; 380764684; 635576381; 82407956; 82407...,2B05:A; 2B05:B; 2B05:C; 2B05:D; 2B05:E; 2B05:F...,GO:0005737; GO:0005829; GO:0070062; GO:0005925...,UniRef100_P61981,UniRef90_P61981,UniRef50_P61981,...,9606,605356; 617665,NaN,10433554; 10486217; 12853948; 15489334; 235725...,AF142498; AB024334; CR541904; CR541925; AC0063...,AAD48408.1; BAA85184.1; CAG46702.1; CAG46723.1...,ENSG00000170027.7,ENST00000307630.5,ENSP00000306330.3,11824616; 11996670; 12364343; 12482592; 150572...
3,P31947,1433S_HUMAN,2810,NP_006133.1,436408756; 306991738; 969812714; 350610438; 35...,1YWT:A; 1YWT:B; 1YZ5:A; 1YZ5:B; 3IQJ:A; 3IQU:A...,GO:0005737; GO:0005829; GO:0070062; GO:0005615...,UniRef100_P31947,UniRef90_P31947,UniRef50_P31947,...,9606,601290,NaN,1390337; 8515476; 9659898; 16710414; 15489334;...,M93010; X57348; AF029081; AF029082; CR541905; ...,AAA59546.1; CAA40623.1; AAC52029.1; AAC52030.1...,ENSG00000175793.12,ENST00000339276.6,ENSP00000340989.4,10969776; 12582028; 12730237; 12787309; 145172...
4,P27348,1433T_HUMAN,10971,NP_006817.1,71042777; 34785143; 32464; 3387922; 119621382;...,2BTP:A; 2BTP:B; 5IQP:A; 5IQP:B; 6BCR:A; 6BCR:B...,GO:0005737; GO:0005829; GO:0070062; GO:0005925...,UniRef100_P27348,UniRef90_P27348,UniRef50_P27348,...,9606,609009,NaN,2015305; 8515476; 15489334; 12665801; 23572552...,X56468; X57347; BT020014; CH471053; CH471053; ...,CAA39840.1; CAA40622.1; AAV38817.1; EAX00977.1...,ENSG00000134308.14,ENST00000238081.8; ENST00000381844.8,ENSP00000238081.3; ENSP00000371267.4,12535517; 15196694; 15930726; 16176975; 162154...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205009,Q9NSA8,Q9NSA8_HUMAN,NaN,NaN,8217330,NaN,NaN,UniRef100_Q9NSA8,UniRef90_Q9NSA8,UniRef50_Q9NSA8,...,9606,NaN,NaN,NaN,Z46940,CAB92527.1,NaN,NaN,NaN,NaN
205010,B7Z3X3,B7Z3X3_HUMAN,1837,NP_001185872.1,221041364; 312147278,NaN,GO:0008270,UniRef100_M0QZ28,UniRef90_Q9Y4J8-15,UniRef50_Q9Y4J8-15,...,9606,NaN,NaN,NaN,AK296450,BAH12359.1,NaN,NaN,NaN,12416719; 12475945; 12604589; 12899872; 158346...
205011,Q3YL84,Q3YL84_HUMAN,NaN,NaN,73544660,NaN,NaN,UniRef100_Q3YL84,UniRef90_Q3YL84,UniRef50_Q3YL84,...,9606,NaN,NaN,16110330,DQ102772,AAZ78118.1,NaN,NaN,NaN,19116388; 11877378; 12110597; 12170762; 123518...
205012,Q53S20,Q53S20_HUMAN,NaN,NaN,62988762,NaN,NaN,UniRef100_Q53S20,UniRef90_Q53S20,UniRef50_Q53S20,...,9606,NaN,NaN,NaN,AC073476,AAY24149.1,NaN,NaN,NaN,NaN
205013,Q69YV8,Q69YV8_HUMAN,NaN,NaN,50949384,NaN,NaN,UniRef100_A0A2K6LC87,UniRef90_A0A2K6LC87,UniRef50_Q8N831,...,9606,NaN,NaN,NaN,AL137639,CAH10705.1,NaN,NaN,NaN,NaN

In [25]:
df_id_conversions.columns

Index(['Uniprot_ID', 'uk1', 'uk2', 'uk3', 'uk4', 'uk5', 'GO_IDs', 'uk6', 'uk7',
       'uk8', 'uk9', 'uk10', 'uk11', 'uk12', 'uk13', 'uk14', 'uk15', 'uk16',
       'ENSG', 'ENST', 'ENSP', 'uk17'],
      dtype='object')

In [26]:
# Create list of ENSP IDs

ensp_id_list = list(df_id_conversions["ENSP"])
ensp_id_list = [str(i).split('; ') for i in ensp_id_list]

In [27]:
# Create list of Uniprot IDs

uniprot_id_list = list(df_id_conversions["Uniprot_ID"])

NameError: name 'uniprot_id_list' is not defined

In [28]:
# Create ENSP to Uniprot ID conversion dictionary

ensp_to_uniprot = {}

for keys, value in zip(ensp_id_list, uniprot_id_list):
    if isinstance(keys, list):
        for key in keys:  
            ensp_to_uniprot[key.split('.')[0]] = value
    else:
        ensp_to_uniprot[keys] = value

In [29]:
# Check for outdated ENSP IDs not included in the Uniprot database

not_in_database = []

for id in scores_df.index:
    if id not in ensp_to_uniprot:
        not_in_database.append(id)

NameError: name 'scores_df' is not defined

In [30]:
# Drop outdated ENSP IDs from our results

scores_df = scores_df.drop(not_in_database)

NameError: name 'scores_df' is not defined

In [31]:
# Add rank columns for each run

rank_columns = ['RVFV', 'DENV', 'LASV', 'RVFVex']

for col in rank_columns:
    scores_df = scores_df.sort_values(col, ascending=False)
    scores_df[f'{col}_rank'] = list(range(1, len(scores_df) + 1))

NameError: name 'scores_df' is not defined

In [32]:
scores_df = scores_df.sort_values('RVFVex', ascending=False)

NameError: name 'scores_df' is not defined

In [33]:
# Convert dataframe index from ENSP to Uniprot IDs

scores_df.rename(index=ensp_to_uniprot, inplace=True)

NameError: name 'scores_df' is not defined

In [34]:
# Create list of GO IDs for each for each Uniprot ID

go_id_list = list(df_id_conversions["GO_IDs"])
go_id_list = [str(i).split('; ') for i in go_id_list]

In [35]:
# Map GO to Uniprot IDs in a dictionary

go_to_uniprot = {}

for value, key in zip(go_id_list, uniprot_id_list):
    go_to_uniprot[key] = value

In [527]:
# Create list of GO IDs in the same order as the dataframe 

go_list = []
for i in scores_df.index:
    go_list.append(go_to_uniprot[i])

In [528]:
scores_df['GO_IDs'] = go_list

In [529]:
# Translate GO IDs to GO terms in a new list

go_term_list = [row[:] for row in go_list]
exclude_list = []

for i in range(len(go_list)):
    for j in range(len(go_list[i])):
        try:
            go_term_list[i][j] = godag[go_list[i][j]].name
        except KeyError:
            exclude_list.append(go_list[i][j])
            go_term_list[i][j] = f'GO ID {go_list[i][j]} not converted'

In [530]:
scores_df['GO_Terms'] = go_term_list

In [120]:
scores_df = scores_df.sort_values('RVFVex', ascending=False)

NameError: name 'scores_df' is not defined

In [121]:

#scores_df[['RVFV', 'GO_Terms']][:15]
scores_df[:15]

NameError: name 'scores_df' is not defined

In [396]:
new_df = scores_df[['LASV', 'GO_Terms']]

In [398]:
results_sheet = "C:\\Users\\socce\\OneDrive\\Documents\\Kehn-Hall Lab Data\\Python\\viral_interact\\Data\\network_prop_results.xlsx"

with pd.ExcelWriter(results_sheet, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    new_df.to_excel(writer, sheet_name='Sheet36', index=True)